//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_InsertorUpdate : BaseProcedure
	{
		private SqlParameter parameterfldmodeltype;

		private SqlParameter parameterfldName;

		private SqlParameter parameterUserID;

		private SqlParameter parameterfldContent;

		public usp_InsertorUpdate()
		{
			base.InitCommand("usp_InsertorUpdate");
			ConfigParameter();
		}

		public System.String fldmodeltype
		{
			get
			{
				return (System.String)this.parameterfldmodeltype.Value;
			}
			set
			{
				this.parameterfldmodeltype.Value=value;
			}
		}

		public System.String fldName
		{
			get
			{
				return (System.String)this.parameterfldName.Value;
			}
			set
			{
				this.parameterfldName.Value=value;
			}
		}

		public System.String UserID
		{
			get
			{
				return (System.String)this.parameterUserID.Value;
			}
			set
			{
				this.parameterUserID.Value=value;
			}
		}

		public System.String fldContent
		{
			get
			{
				return (System.String)this.parameterfldContent.Value;
			}
			set
			{
				this.parameterfldContent.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterfldmodeltype=new SqlParameter();
			this.parameterfldmodeltype.ParameterName="@fldmodeltype";
			this.parameterfldmodeltype.SqlDbType=SqlDbType.VarChar;
			this.parameterfldmodeltype.Size=10;
			this.parameterfldmodeltype.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldmodeltype);
			//--------------------------------------------------------
			this.parameterfldName=new SqlParameter();
			this.parameterfldName.ParameterName="@fldName";
			this.parameterfldName.SqlDbType=SqlDbType.VarChar;
			this.parameterfldName.Size=500;
			this.parameterfldName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldName);
			//--------------------------------------------------------
			this.parameterUserID=new SqlParameter();
			this.parameterUserID.ParameterName="@UserID";
			this.parameterUserID.SqlDbType=SqlDbType.VarChar;
			this.parameterUserID.Size=5;
			this.parameterUserID.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterUserID);
			//--------------------------------------------------------
			this.parameterfldContent=new SqlParameter();
			this.parameterfldContent.ParameterName="@fldContent";
			this.parameterfldContent.SqlDbType=SqlDbType.VarChar;
			this.parameterfldContent.Size=-1;
			this.parameterfldContent.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldContent);
		}
	}
}
