//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblFW_User_Update : BaseProcedure
	{
		private SqlParameter parameterold_fldAutoID;

		private SqlParameter parameterold_fldUserName;

		private SqlParameter parameterold_fldUserDesc;

		private SqlParameter parameterold_fldDeptID;

		private SqlParameter parameterold_fldCityID;

		private SqlParameter parameterold_fldDuty;

		private SqlParameter parameterold_fldHeaderShip;

		private SqlParameter parameterold_fldSex;

		private SqlParameter parameterold_fldEducation;

		private SqlParameter parameterold_fldBirthday;

		private SqlParameter parameterold_fldEmail;

		private SqlParameter parameterold_fldPhone;

		private SqlParameter parameterold_fldMobile;

		private SqlParameter parameterold_fldActive;

		private SqlParameter parameterold_fldMemo;

		private SqlParameter parameternew_fldUserName;

		private SqlParameter parameternew_fldUserDesc;

		private SqlParameter parameternew_fldPassword;

		private SqlParameter parameternew_fldDeptID;

		private SqlParameter parameternew_fldCityID;

		private SqlParameter parameternew_fldDuty;

		private SqlParameter parameternew_fldHeaderShip;

		private SqlParameter parameternew_fldSex;

		private SqlParameter parameternew_fldEducation;

		private SqlParameter parameternew_fldBirthday;

		private SqlParameter parameternew_fldEmail;

		private SqlParameter parameternew_fldPhone;

		private SqlParameter parameternew_fldMobile;

		private SqlParameter parameternew_fldActive;

		private SqlParameter parameternew_fldMemo;

		public usp_tblFW_User_Update()
		{
			base.InitCommand("usp_tblFW_User_Update");
			ConfigParameter();
		}

		public System.Int32 old_fldAutoID
		{
			get
			{
				return (System.Int32)this.parameterold_fldAutoID.Value;
			}
			set
			{
				this.parameterold_fldAutoID.Value=value;
			}
		}

		public System.String old_fldUserName
		{
			get
			{
				return (System.String)this.parameterold_fldUserName.Value;
			}
			set
			{
				this.parameterold_fldUserName.Value=value;
			}
		}

		public System.String old_fldUserDesc
		{
			get
			{
				return (System.String)this.parameterold_fldUserDesc.Value;
			}
			set
			{
				this.parameterold_fldUserDesc.Value=value;
			}
		}

		public System.Int32 old_fldDeptID
		{
			get
			{
				return (System.Int32)this.parameterold_fldDeptID.Value;
			}
			set
			{
				this.parameterold_fldDeptID.Value=value;
			}
		}

		public System.Int32 old_fldCityID
		{
			get
			{
				return (System.Int32)this.parameterold_fldCityID.Value;
			}
			set
			{
				this.parameterold_fldCityID.Value=value;
			}
		}

		public System.String old_fldDuty
		{
			get
			{
				return (System.String)this.parameterold_fldDuty.Value;
			}
			set
			{
				this.parameterold_fldDuty.Value=value;
			}
		}

		public System.String old_fldHeaderShip
		{
			get
			{
				return (System.String)this.parameterold_fldHeaderShip.Value;
			}
			set
			{
				this.parameterold_fldHeaderShip.Value=value;
			}
		}

		public System.Boolean old_fldSex
		{
			get
			{
				return (System.Boolean)this.parameterold_fldSex.Value;
			}
			set
			{
				this.parameterold_fldSex.Value=value;
			}
		}

		public System.Int16 old_fldEducation
		{
			get
			{
				return (System.Int16)this.parameterold_fldEducation.Value;
			}
			set
			{
				this.parameterold_fldEducation.Value=value;
			}
		}

		public System.DateTime old_fldBirthday
		{
			get
			{
				return (System.DateTime)this.parameterold_fldBirthday.Value;
			}
			set
			{
				this.parameterold_fldBirthday.Value=value;
			}
		}

		public System.String old_fldEmail
		{
			get
			{
				return (System.String)this.parameterold_fldEmail.Value;
			}
			set
			{
				this.parameterold_fldEmail.Value=value;
			}
		}

		public System.String old_fldPhone
		{
			get
			{
				return (System.String)this.parameterold_fldPhone.Value;
			}
			set
			{
				this.parameterold_fldPhone.Value=value;
			}
		}

		public System.String old_fldMobile
		{
			get
			{
				return (System.String)this.parameterold_fldMobile.Value;
			}
			set
			{
				this.parameterold_fldMobile.Value=value;
			}
		}

		public System.Boolean old_fldActive
		{
			get
			{
				return (System.Boolean)this.parameterold_fldActive.Value;
			}
			set
			{
				this.parameterold_fldActive.Value=value;
			}
		}

		public System.String old_fldMemo
		{
			get
			{
				return (System.String)this.parameterold_fldMemo.Value;
			}
			set
			{
				this.parameterold_fldMemo.Value=value;
			}
		}

		public System.String new_fldUserName
		{
			get
			{
				return (System.String)this.parameternew_fldUserName.Value;
			}
			set
			{
				this.parameternew_fldUserName.Value=value;
			}
		}

		public System.String new_fldUserDesc
		{
			get
			{
				return (System.String)this.parameternew_fldUserDesc.Value;
			}
			set
			{
				this.parameternew_fldUserDesc.Value=value;
			}
		}

		public System.String new_fldPassword
		{
			get
			{
				return (System.String)this.parameternew_fldPassword.Value;
			}
			set
			{
				this.parameternew_fldPassword.Value=value;
			}
		}

		public System.Int32 new_fldDeptID
		{
			get
			{
				return (System.Int32)this.parameternew_fldDeptID.Value;
			}
			set
			{
				this.parameternew_fldDeptID.Value=value;
			}
		}

		public System.Int32 new_fldCityID
		{
			get
			{
				return (System.Int32)this.parameternew_fldCityID.Value;
			}
			set
			{
				this.parameternew_fldCityID.Value=value;
			}
		}

		public System.String new_fldDuty
		{
			get
			{
				return (System.String)this.parameternew_fldDuty.Value;
			}
			set
			{
				this.parameternew_fldDuty.Value=value;
			}
		}

		public System.String new_fldHeaderShip
		{
			get
			{
				return (System.String)this.parameternew_fldHeaderShip.Value;
			}
			set
			{
				this.parameternew_fldHeaderShip.Value=value;
			}
		}

		public System.Boolean new_fldSex
		{
			get
			{
				return (System.Boolean)this.parameternew_fldSex.Value;
			}
			set
			{
				this.parameternew_fldSex.Value=value;
			}
		}

		public System.Int16 new_fldEducation
		{
			get
			{
				return (System.Int16)this.parameternew_fldEducation.Value;
			}
			set
			{
				this.parameternew_fldEducation.Value=value;
			}
		}

		public System.DateTime new_fldBirthday
		{
			get
			{
				return (System.DateTime)this.parameternew_fldBirthday.Value;
			}
			set
			{
				this.parameternew_fldBirthday.Value=value;
			}
		}

		public System.String new_fldEmail
		{
			get
			{
				return (System.String)this.parameternew_fldEmail.Value;
			}
			set
			{
				this.parameternew_fldEmail.Value=value;
			}
		}

		public System.String new_fldPhone
		{
			get
			{
				return (System.String)this.parameternew_fldPhone.Value;
			}
			set
			{
				this.parameternew_fldPhone.Value=value;
			}
		}

		public System.String new_fldMobile
		{
			get
			{
				return (System.String)this.parameternew_fldMobile.Value;
			}
			set
			{
				this.parameternew_fldMobile.Value=value;
			}
		}

		public System.Boolean new_fldActive
		{
			get
			{
				return (System.Boolean)this.parameternew_fldActive.Value;
			}
			set
			{
				this.parameternew_fldActive.Value=value;
			}
		}

		public System.String new_fldMemo
		{
			get
			{
				return (System.String)this.parameternew_fldMemo.Value;
			}
			set
			{
				this.parameternew_fldMemo.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterold_fldAutoID=new SqlParameter();
			this.parameterold_fldAutoID.ParameterName="@old_fldAutoID";
			this.parameterold_fldAutoID.SqlDbType=SqlDbType.Int;
			this.parameterold_fldAutoID.Size=4;
			this.parameterold_fldAutoID.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldAutoID);
			//--------------------------------------------------------
			this.parameterold_fldUserName=new SqlParameter();
			this.parameterold_fldUserName.ParameterName="@old_fldUserName";
			this.parameterold_fldUserName.SqlDbType=SqlDbType.VarChar;
			this.parameterold_fldUserName.Size=20;
			this.parameterold_fldUserName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldUserName);
			//--------------------------------------------------------
			this.parameterold_fldUserDesc=new SqlParameter();
			this.parameterold_fldUserDesc.ParameterName="@old_fldUserDesc";
			this.parameterold_fldUserDesc.SqlDbType=SqlDbType.VarChar;
			this.parameterold_fldUserDesc.Size=20;
			this.parameterold_fldUserDesc.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldUserDesc);
			//--------------------------------------------------------
			this.parameterold_fldDeptID=new SqlParameter();
			this.parameterold_fldDeptID.ParameterName="@old_fldDeptID";
			this.parameterold_fldDeptID.SqlDbType=SqlDbType.Int;
			this.parameterold_fldDeptID.Size=4;
			this.parameterold_fldDeptID.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldDeptID);
			//--------------------------------------------------------
			this.parameterold_fldCityID=new SqlParameter();
			this.parameterold_fldCityID.ParameterName="@old_fldCityID";
			this.parameterold_fldCityID.SqlDbType=SqlDbType.Int;
			this.parameterold_fldCityID.Size=4;
			this.parameterold_fldCityID.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldCityID);
			//--------------------------------------------------------
			this.parameterold_fldDuty=new SqlParameter();
			this.parameterold_fldDuty.ParameterName="@old_fldDuty";
			this.parameterold_fldDuty.SqlDbType=SqlDbType.VarChar;
			this.parameterold_fldDuty.Size=30;
			this.parameterold_fldDuty.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldDuty);
			//--------------------------------------------------------
			this.parameterold_fldHeaderShip=new SqlParameter();
			this.parameterold_fldHeaderShip.ParameterName="@old_fldHeaderShip";
			this.parameterold_fldHeaderShip.SqlDbType=SqlDbType.VarChar;
			this.parameterold_fldHeaderShip.Size=30;
			this.parameterold_fldHeaderShip.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldHeaderShip);
			//--------------------------------------------------------
			this.parameterold_fldSex=new SqlParameter();
			this.parameterold_fldSex.ParameterName="@old_fldSex";
			this.parameterold_fldSex.SqlDbType=SqlDbType.Bit;
			this.parameterold_fldSex.Size=1;
			this.parameterold_fldSex.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldSex);
			//--------------------------------------------------------
			this.parameterold_fldEducation=new SqlParameter();
			this.parameterold_fldEducation.ParameterName="@old_fldEducation";
			this.parameterold_fldEducation.SqlDbType=SqlDbType.SmallInt;
			this.parameterold_fldEducation.Size=2;
			this.parameterold_fldEducation.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldEducation);
			//--------------------------------------------------------
			this.parameterold_fldBirthday=new SqlParameter();
			this.parameterold_fldBirthday.ParameterName="@old_fldBirthday";
			this.parameterold_fldBirthday.SqlDbType=SqlDbType.DateTime;
			this.parameterold_fldBirthday.Size=8;
			this.parameterold_fldBirthday.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldBirthday);
			//--------------------------------------------------------
			this.parameterold_fldEmail=new SqlParameter();
			this.parameterold_fldEmail.ParameterName="@old_fldEmail";
			this.parameterold_fldEmail.SqlDbType=SqlDbType.VarChar;
			this.parameterold_fldEmail.Size=50;
			this.parameterold_fldEmail.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldEmail);
			//--------------------------------------------------------
			this.parameterold_fldPhone=new SqlParameter();
			this.parameterold_fldPhone.ParameterName="@old_fldPhone";
			this.parameterold_fldPhone.SqlDbType=SqlDbType.VarChar;
			this.parameterold_fldPhone.Size=30;
			this.parameterold_fldPhone.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldPhone);
			//--------------------------------------------------------
			this.parameterold_fldMobile=new SqlParameter();
			this.parameterold_fldMobile.ParameterName="@old_fldMobile";
			this.parameterold_fldMobile.SqlDbType=SqlDbType.VarChar;
			this.parameterold_fldMobile.Size=11;
			this.parameterold_fldMobile.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldMobile);
			//--------------------------------------------------------
			this.parameterold_fldActive=new SqlParameter();
			this.parameterold_fldActive.ParameterName="@old_fldActive";
			this.parameterold_fldActive.SqlDbType=SqlDbType.Bit;
			this.parameterold_fldActive.Size=1;
			this.parameterold_fldActive.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldActive);
			//--------------------------------------------------------
			this.parameterold_fldMemo=new SqlParameter();
			this.parameterold_fldMemo.ParameterName="@old_fldMemo";
			this.parameterold_fldMemo.SqlDbType=SqlDbType.VarChar;
			this.parameterold_fldMemo.Size=400;
			this.parameterold_fldMemo.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterold_fldMemo);
			//--------------------------------------------------------
			this.parameternew_fldUserName=new SqlParameter();
			this.parameternew_fldUserName.ParameterName="@new_fldUserName";
			this.parameternew_fldUserName.SqlDbType=SqlDbType.VarChar;
			this.parameternew_fldUserName.Size=20;
			this.parameternew_fldUserName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldUserName);
			//--------------------------------------------------------
			this.parameternew_fldUserDesc=new SqlParameter();
			this.parameternew_fldUserDesc.ParameterName="@new_fldUserDesc";
			this.parameternew_fldUserDesc.SqlDbType=SqlDbType.VarChar;
			this.parameternew_fldUserDesc.Size=20;
			this.parameternew_fldUserDesc.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldUserDesc);
			//--------------------------------------------------------
			this.parameternew_fldPassword=new SqlParameter();
			this.parameternew_fldPassword.ParameterName="@new_fldPassword";
			this.parameternew_fldPassword.SqlDbType=SqlDbType.VarChar;
			this.parameternew_fldPassword.Size=32;
			this.parameternew_fldPassword.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldPassword);
			//--------------------------------------------------------
			this.parameternew_fldDeptID=new SqlParameter();
			this.parameternew_fldDeptID.ParameterName="@new_fldDeptID";
			this.parameternew_fldDeptID.SqlDbType=SqlDbType.Int;
			this.parameternew_fldDeptID.Size=4;
			this.parameternew_fldDeptID.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldDeptID);
			//--------------------------------------------------------
			this.parameternew_fldCityID=new SqlParameter();
			this.parameternew_fldCityID.ParameterName="@new_fldCityID";
			this.parameternew_fldCityID.SqlDbType=SqlDbType.Int;
			this.parameternew_fldCityID.Size=4;
			this.parameternew_fldCityID.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldCityID);
			//--------------------------------------------------------
			this.parameternew_fldDuty=new SqlParameter();
			this.parameternew_fldDuty.ParameterName="@new_fldDuty";
			this.parameternew_fldDuty.SqlDbType=SqlDbType.VarChar;
			this.parameternew_fldDuty.Size=30;
			this.parameternew_fldDuty.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldDuty);
			//--------------------------------------------------------
			this.parameternew_fldHeaderShip=new SqlParameter();
			this.parameternew_fldHeaderShip.ParameterName="@new_fldHeaderShip";
			this.parameternew_fldHeaderShip.SqlDbType=SqlDbType.VarChar;
			this.parameternew_fldHeaderShip.Size=30;
			this.parameternew_fldHeaderShip.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldHeaderShip);
			//--------------------------------------------------------
			this.parameternew_fldSex=new SqlParameter();
			this.parameternew_fldSex.ParameterName="@new_fldSex";
			this.parameternew_fldSex.SqlDbType=SqlDbType.Bit;
			this.parameternew_fldSex.Size=1;
			this.parameternew_fldSex.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldSex);
			//--------------------------------------------------------
			this.parameternew_fldEducation=new SqlParameter();
			this.parameternew_fldEducation.ParameterName="@new_fldEducation";
			this.parameternew_fldEducation.SqlDbType=SqlDbType.SmallInt;
			this.parameternew_fldEducation.Size=2;
			this.parameternew_fldEducation.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldEducation);
			//--------------------------------------------------------
			this.parameternew_fldBirthday=new SqlParameter();
			this.parameternew_fldBirthday.ParameterName="@new_fldBirthday";
			this.parameternew_fldBirthday.SqlDbType=SqlDbType.DateTime;
			this.parameternew_fldBirthday.Size=8;
			this.parameternew_fldBirthday.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldBirthday);
			//--------------------------------------------------------
			this.parameternew_fldEmail=new SqlParameter();
			this.parameternew_fldEmail.ParameterName="@new_fldEmail";
			this.parameternew_fldEmail.SqlDbType=SqlDbType.VarChar;
			this.parameternew_fldEmail.Size=50;
			this.parameternew_fldEmail.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldEmail);
			//--------------------------------------------------------
			this.parameternew_fldPhone=new SqlParameter();
			this.parameternew_fldPhone.ParameterName="@new_fldPhone";
			this.parameternew_fldPhone.SqlDbType=SqlDbType.VarChar;
			this.parameternew_fldPhone.Size=30;
			this.parameternew_fldPhone.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldPhone);
			//--------------------------------------------------------
			this.parameternew_fldMobile=new SqlParameter();
			this.parameternew_fldMobile.ParameterName="@new_fldMobile";
			this.parameternew_fldMobile.SqlDbType=SqlDbType.VarChar;
			this.parameternew_fldMobile.Size=11;
			this.parameternew_fldMobile.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldMobile);
			//--------------------------------------------------------
			this.parameternew_fldActive=new SqlParameter();
			this.parameternew_fldActive.ParameterName="@new_fldActive";
			this.parameternew_fldActive.SqlDbType=SqlDbType.Bit;
			this.parameternew_fldActive.Size=1;
			this.parameternew_fldActive.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldActive);
			//--------------------------------------------------------
			this.parameternew_fldMemo=new SqlParameter();
			this.parameternew_fldMemo.ParameterName="@new_fldMemo";
			this.parameternew_fldMemo.SqlDbType=SqlDbType.VarChar;
			this.parameternew_fldMemo.Size=400;
			this.parameternew_fldMemo.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameternew_fldMemo);
		}
	}
}
