//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_GetPointNameorLevel_shibao : BaseProcedure
	{
		private SqlParameter parametersWhere;

		private SqlParameter parameterview;

		private SqlParameter parametertype;

		public usp_GetPointNameorLevel_shibao()
		{
			base.InitCommand("usp_GetPointNameorLevel_shibao");
			ConfigParameter();
		}

		public System.String sWhere
		{
			get
			{
				return (System.String)this.parametersWhere.Value;
			}
			set
			{
				this.parametersWhere.Value=value;
			}
		}

		public System.String view
		{
			get
			{
				return (System.String)this.parameterview.Value;
			}
			set
			{
				this.parameterview.Value=value;
			}
		}

		public System.String type
		{
			get
			{
				return (System.String)this.parametertype.Value;
			}
			set
			{
				this.parametertype.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parametersWhere=new SqlParameter();
			this.parametersWhere.ParameterName="@sWhere";
			this.parametersWhere.SqlDbType=SqlDbType.VarChar;
			this.parametersWhere.Size=-1;
			this.parametersWhere.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parametersWhere);
			//--------------------------------------------------------
			this.parameterview=new SqlParameter();
			this.parameterview.ParameterName="@view";
			this.parameterview.SqlDbType=SqlDbType.VarChar;
			this.parameterview.Size=50;
			this.parameterview.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterview);
			//--------------------------------------------------------
			this.parametertype=new SqlParameter();
			this.parametertype.ParameterName="@type";
			this.parametertype.SqlDbType=SqlDbType.VarChar;
			this.parametertype.Size=20;
			this.parametertype.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parametertype);
		}
	}
}
