//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblEQIW_R_Report_SectionApprise : BaseProcedure
	{
		private SqlParameter parameterTimeType;

		private SqlParameter parameterBeginDate;

		private SqlParameter parameterEndDate;

		private SqlParameter parameterfldRSC;

		private SqlParameter parameterfldRSCode;

		private SqlParameter parameterfldStandardName;

		private SqlParameter parameterfldLevel;

		private SqlParameter parameterfldItemCode;

		private SqlParameter parameterDecCarry;

		private SqlParameter parameterIsPre;

		private SqlParameter parameterIsYear;

		private SqlParameter parameterIsTotal;

		private SqlParameter parameterIsDetail;

		private SqlParameter parameterSTatType;

		public usp_tblEQIW_R_Report_SectionApprise()
		{
			base.InitCommand("usp_tblEQIW_R_Report_SectionApprise");
			ConfigParameter();
		}

		public System.String TimeType
		{
			get
			{
				return (System.String)this.parameterTimeType.Value;
			}
			set
			{
				this.parameterTimeType.Value=value;
			}
		}

		public System.String BeginDate
		{
			get
			{
				return (System.String)this.parameterBeginDate.Value;
			}
			set
			{
				this.parameterBeginDate.Value=value;
			}
		}

		public System.String EndDate
		{
			get
			{
				return (System.String)this.parameterEndDate.Value;
			}
			set
			{
				this.parameterEndDate.Value=value;
			}
		}

		public System.String fldRSC
		{
			get
			{
				return (System.String)this.parameterfldRSC.Value;
			}
			set
			{
				this.parameterfldRSC.Value=value;
			}
		}

		public System.String fldRSCode
		{
			get
			{
				return (System.String)this.parameterfldRSCode.Value;
			}
			set
			{
				this.parameterfldRSCode.Value=value;
			}
		}

		public System.String fldStandardName
		{
			get
			{
				return (System.String)this.parameterfldStandardName.Value;
			}
			set
			{
				this.parameterfldStandardName.Value=value;
			}
		}

		public System.Int16 fldLevel
		{
			get
			{
				return (System.Int16)this.parameterfldLevel.Value;
			}
			set
			{
				this.parameterfldLevel.Value=value;
			}
		}

		public System.String fldItemCode
		{
			get
			{
				return (System.String)this.parameterfldItemCode.Value;
			}
			set
			{
				this.parameterfldItemCode.Value=value;
			}
		}

		public System.String DecCarry
		{
			get
			{
				return (System.String)this.parameterDecCarry.Value;
			}
			set
			{
				this.parameterDecCarry.Value=value;
			}
		}

		public System.Int32 IsPre
		{
			get
			{
				return (System.Int32)this.parameterIsPre.Value;
			}
			set
			{
				this.parameterIsPre.Value=value;
			}
		}

		public System.Int32 IsYear
		{
			get
			{
				return (System.Int32)this.parameterIsYear.Value;
			}
			set
			{
				this.parameterIsYear.Value=value;
			}
		}

		public System.Int32 IsTotal
		{
			get
			{
				return (System.Int32)this.parameterIsTotal.Value;
			}
			set
			{
				this.parameterIsTotal.Value=value;
			}
		}

		public System.Int32 IsDetail
		{
			get
			{
				return (System.Int32)this.parameterIsDetail.Value;
			}
			set
			{
				this.parameterIsDetail.Value=value;
			}
		}

		public System.Int16 STatType
		{
			get
			{
				return (System.Int16)this.parameterSTatType.Value;
			}
			set
			{
				this.parameterSTatType.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterTimeType=new SqlParameter();
			this.parameterTimeType.ParameterName="@TimeType";
			this.parameterTimeType.SqlDbType=SqlDbType.VarChar;
			this.parameterTimeType.Size=10;
			this.parameterTimeType.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterTimeType);
			//--------------------------------------------------------
			this.parameterBeginDate=new SqlParameter();
			this.parameterBeginDate.ParameterName="@BeginDate";
			this.parameterBeginDate.SqlDbType=SqlDbType.VarChar;
			this.parameterBeginDate.Size=10;
			this.parameterBeginDate.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterBeginDate);
			//--------------------------------------------------------
			this.parameterEndDate=new SqlParameter();
			this.parameterEndDate.ParameterName="@EndDate";
			this.parameterEndDate.SqlDbType=SqlDbType.VarChar;
			this.parameterEndDate.Size=10;
			this.parameterEndDate.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterEndDate);
			//--------------------------------------------------------
			this.parameterfldRSC=new SqlParameter();
			this.parameterfldRSC.ParameterName="@fldRSC";
			this.parameterfldRSC.SqlDbType=SqlDbType.VarChar;
			this.parameterfldRSC.Size=10;
			this.parameterfldRSC.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldRSC);
			//--------------------------------------------------------
			this.parameterfldRSCode=new SqlParameter();
			this.parameterfldRSCode.ParameterName="@fldRSCode";
			this.parameterfldRSCode.SqlDbType=SqlDbType.VarChar;
			this.parameterfldRSCode.Size=-1;
			this.parameterfldRSCode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldRSCode);
			//--------------------------------------------------------
			this.parameterfldStandardName=new SqlParameter();
			this.parameterfldStandardName.ParameterName="@fldStandardName";
			this.parameterfldStandardName.SqlDbType=SqlDbType.VarChar;
			this.parameterfldStandardName.Size=100;
			this.parameterfldStandardName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldStandardName);
			//--------------------------------------------------------
			this.parameterfldLevel=new SqlParameter();
			this.parameterfldLevel.ParameterName="@fldLevel";
			this.parameterfldLevel.SqlDbType=SqlDbType.SmallInt;
			this.parameterfldLevel.Size=2;
			this.parameterfldLevel.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldLevel);
			//--------------------------------------------------------
			this.parameterfldItemCode=new SqlParameter();
			this.parameterfldItemCode.ParameterName="@fldItemCode";
			this.parameterfldItemCode.SqlDbType=SqlDbType.VarChar;
			this.parameterfldItemCode.Size=6000;
			this.parameterfldItemCode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldItemCode);
			//--------------------------------------------------------
			this.parameterDecCarry=new SqlParameter();
			this.parameterDecCarry.ParameterName="@DecCarry";
			this.parameterDecCarry.SqlDbType=SqlDbType.VarChar;
			this.parameterDecCarry.Size=1;
			this.parameterDecCarry.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterDecCarry);
			//--------------------------------------------------------
			this.parameterIsPre=new SqlParameter();
			this.parameterIsPre.ParameterName="@IsPre";
			this.parameterIsPre.SqlDbType=SqlDbType.Int;
			this.parameterIsPre.Size=4;
			this.parameterIsPre.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterIsPre);
			//--------------------------------------------------------
			this.parameterIsYear=new SqlParameter();
			this.parameterIsYear.ParameterName="@IsYear";
			this.parameterIsYear.SqlDbType=SqlDbType.Int;
			this.parameterIsYear.Size=4;
			this.parameterIsYear.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterIsYear);
			//--------------------------------------------------------
			this.parameterIsTotal=new SqlParameter();
			this.parameterIsTotal.ParameterName="@IsTotal";
			this.parameterIsTotal.SqlDbType=SqlDbType.Int;
			this.parameterIsTotal.Size=4;
			this.parameterIsTotal.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterIsTotal);
			//--------------------------------------------------------
			this.parameterIsDetail=new SqlParameter();
			this.parameterIsDetail.ParameterName="@IsDetail";
			this.parameterIsDetail.SqlDbType=SqlDbType.Int;
			this.parameterIsDetail.Size=4;
			this.parameterIsDetail.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterIsDetail);
			//--------------------------------------------------------
			this.parameterSTatType=new SqlParameter();
			this.parameterSTatType.ParameterName="@STatType";
			this.parameterSTatType.SqlDbType=SqlDbType.SmallInt;
			this.parameterSTatType.Size=2;
			this.parameterSTatType.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterSTatType);
		}
	}
}
