//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_IsRuleH5 : BaseProcedure
	{
		private SqlParameter parameterOutInt;

		private SqlParameter parameterMemberId;

		private SqlParameter parameterOrderID;

        private SqlParameter parameterAmount;

        private SqlParameter parameterPayType;

        private SqlParameter parameterSecretKey;

        private SqlParameter parameterRateName;

        public usp_IsRuleH5()
		{
			base.InitCommand("usp_IsRuleH5");
			ConfigParameter();
		}

		public System.Int32 OutInt
        {
			get
			{
				return (System.Int32)this.parameterOutInt.Value;
			}
			set
			{
				this.parameterOutInt.Value=value;
			}
		}

		public System.String MemberId
        {
			get
			{
				return (System.String)this.parameterMemberId.Value;
			}
			set
			{
				this.parameterMemberId.Value=value;
			}
		}

		public System.String OrderID
        {
			get
			{
				return (System.String)this.parameterOrderID.Value;
			}
			set
			{
				this.parameterOrderID.Value=value;
			}
		}

        public System.Decimal Amount
        {
            get
            {
                return (System.Decimal)this.parameterAmount.Value;
            }
            set
            {
                this.parameterAmount.Value = value;
            }
        }

        public System.String PayType
        {
            get
            {
                return (System.String)this.parameterPayType.Value;
            }
            set
            {
                this.parameterPayType.Value = value;
            }
        }

        public System.String SecretKey
        {
            get
            {
                return (System.String)this.parameterSecretKey.Value;
            }
            set
            {
                this.parameterSecretKey.Value = value;
            }
        }

        public System.String RateName
        {
            get
            {
                return (System.String)this.parameterRateName.Value;
            }
            set
            {
                this.parameterRateName.Value = value;
            }
        }
        public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterOutInt = new SqlParameter();
			this.parameterOutInt.ParameterName= "@OutInt";
			this.parameterOutInt.SqlDbType=SqlDbType.Int;
			this.parameterOutInt.Size=50;
			this.parameterOutInt.Direction=ParameterDirection.Output;
			base.m_cmd.Parameters.Add(this.parameterOutInt);
			//--------------------------------------------------------
			this.parameterMemberId = new SqlParameter();
			this.parameterMemberId.ParameterName= "@MemberId";
			this.parameterMemberId.SqlDbType=SqlDbType.VarChar;
            this.parameterMemberId.Size = 50;
			this.parameterMemberId.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterMemberId);
			//--------------------------------------------------------
			this.parameterOrderID = new SqlParameter();
			this.parameterOrderID.ParameterName= "@OrderID";
			this.parameterOrderID.SqlDbType=SqlDbType.VarChar;
			this.parameterOrderID.Size=50;
			this.parameterOrderID.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterOrderID);
            //--------------------------------------------------------
            this.parameterAmount = new SqlParameter();
            this.parameterAmount.ParameterName = "@Amount";
            this.parameterAmount.SqlDbType = SqlDbType.Decimal;
            this.parameterAmount.Size = 50;
            this.parameterAmount.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterAmount);
            //--------------------------------------------------------
            this.parameterPayType = new SqlParameter();
            this.parameterPayType.ParameterName = "@PayType";
            this.parameterPayType.SqlDbType = SqlDbType.VarChar;
            this.parameterPayType.Size = 50;
            this.parameterPayType.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterPayType);
            //--------------------------------------------------------
            this.parameterSecretKey = new SqlParameter();
            this.parameterSecretKey.ParameterName = "@SecretKey";
            this.parameterSecretKey.SqlDbType = SqlDbType.VarChar;
            this.parameterSecretKey.Size = 50;
            this.parameterSecretKey.Direction = ParameterDirection.Output;
            base.m_cmd.Parameters.Add(this.parameterSecretKey);
            //--------------------------------------------------------
            this.parameterRateName = new SqlParameter();
            this.parameterRateName.ParameterName = "@RateName";
            this.parameterRateName.SqlDbType = SqlDbType.VarChar;
            this.parameterRateName.Size = 50;
            this.parameterRateName.Direction = ParameterDirection.Output;
            base.m_cmd.Parameters.Add(this.parameterRateName);
        }
	}
}
