//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblEQIA_RD_Item_ByCode : BaseProcedure
	{
		private SqlParameter parametercode;

		public usp_tblEQIA_RD_Item_ByCode()
		{
			base.InitCommand("usp_tblEQIA_RD_Item_ByCode");
			ConfigParameter();
		}

		public System.String code
		{
			get
			{
				return (System.String)this.parametercode.Value;
			}
			set
			{
				this.parametercode.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parametercode=new SqlParameter();
			this.parametercode.ParameterName="@code";
			this.parametercode.SqlDbType=SqlDbType.VarChar;
			this.parametercode.Size=-1;
			this.parametercode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parametercode);
		}
	}
}
