//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblEQIW_R_ItemSTD_GetSTD : BaseProcedure
	{
		private SqlParameter parameterstritemCode;

		private SqlParameter parameterEdition;

		public usp_tblEQIW_R_ItemSTD_GetSTD()
		{
			base.InitCommand("usp_tblEQIW_R_ItemSTD_GetSTD");
			ConfigParameter();
		}

		public System.String stritemCode
		{
			get
			{
				return (System.String)this.parameterstritemCode.Value;
			}
			set
			{
				this.parameterstritemCode.Value=value;
			}
		}

		public System.String Edition
		{
			get
			{
				return (System.String)this.parameterEdition.Value;
			}
			set
			{
				this.parameterEdition.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterstritemCode=new SqlParameter();
			this.parameterstritemCode.ParameterName="@stritemCode";
			this.parameterstritemCode.SqlDbType=SqlDbType.NVarChar;
			this.parameterstritemCode.Size=-1;
			this.parameterstritemCode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterstritemCode);
			//--------------------------------------------------------
			this.parameterEdition=new SqlParameter();
			this.parameterEdition.ParameterName="@Edition";
			this.parameterEdition.SqlDbType=SqlDbType.VarChar;
			this.parameterEdition.Size=20;
			this.parameterEdition.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterEdition);
		}
	}
}
