//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblDictionary_Insert : BaseProcedure
	{
		private SqlParameter parameterfldAutoID;

		private SqlParameter parameterfldName;

		private SqlParameter parameterfldKey;

		private SqlParameter parameterfldParentID;

		public usp_tblDictionary_Insert()
		{
			base.InitCommand("usp_tblDictionary_Insert");
			ConfigParameter();
		}

		public System.Int32 fldAutoID
		{
			get
			{
				return (System.Int32)this.parameterfldAutoID.Value;
			}
			set
			{
				this.parameterfldAutoID.Value=value;
			}
		}

		public System.String fldName
		{
			get
			{
				return (System.String)this.parameterfldName.Value;
			}
			set
			{
				this.parameterfldName.Value=value;
			}
		}

		public System.String fldKey
		{
			get
			{
				return (System.String)this.parameterfldKey.Value;
			}
			set
			{
				this.parameterfldKey.Value=value;
			}
		}

		public System.Int32 fldParentID
		{
			get
			{
				return (System.Int32)this.parameterfldParentID.Value;
			}
			set
			{
				this.parameterfldParentID.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterfldAutoID=new SqlParameter();
			this.parameterfldAutoID.ParameterName="@fldAutoID";
			this.parameterfldAutoID.SqlDbType=SqlDbType.Int;
			this.parameterfldAutoID.Size=4;
			this.parameterfldAutoID.Direction=ParameterDirection.InputOutput;
			base.m_cmd.Parameters.Add(this.parameterfldAutoID);
			//--------------------------------------------------------
			this.parameterfldName=new SqlParameter();
			this.parameterfldName.ParameterName="@fldName";
			this.parameterfldName.SqlDbType=SqlDbType.VarChar;
			this.parameterfldName.Size=200;
			this.parameterfldName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldName);
			//--------------------------------------------------------
			this.parameterfldKey=new SqlParameter();
			this.parameterfldKey.ParameterName="@fldKey";
			this.parameterfldKey.SqlDbType=SqlDbType.VarChar;
			this.parameterfldKey.Size=200;
			this.parameterfldKey.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldKey);
			//--------------------------------------------------------
			this.parameterfldParentID=new SqlParameter();
			this.parameterfldParentID.ParameterName="@fldParentID";
			this.parameterfldParentID.SqlDbType=SqlDbType.Int;
			this.parameterfldParentID.Size=4;
			this.parameterfldParentID.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldParentID);
		}
	}
}
