//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_execSqlText : BaseProcedure
	{
		private SqlParameter parametersqlText;

		public usp_execSqlText()
		{
			base.InitCommand("usp_execSqlText");
			ConfigParameter();
		}

		public System.String sqlText
		{
			get
			{
				return (System.String)this.parametersqlText.Value;
			}
			set
			{
				this.parametersqlText.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parametersqlText=new SqlParameter();
			this.parametersqlText.ParameterName="@sqlText";
			this.parametersqlText.SqlDbType=SqlDbType.VarChar;
			this.parametersqlText.Size=-1;
			this.parametersqlText.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parametersqlText);
		}
	}
}
