//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblEQIA_RPI_AQI_CityDay_Midd_TimeQuantumSelect : BaseProcedure
	{
		private SqlParameter parameterstcode;

		private SqlParameter parameterBeginDate;

		private SqlParameter parameterEndDate;

		public usp_tblEQIA_RPI_AQI_CityDay_Midd_TimeQuantumSelect()
		{
			base.InitCommand("usp_tblEQIA_RPI_AQI_CityDay_Midd_TimeQuantumSelect");
			ConfigParameter();
		}

		public System.String stcode
		{
			get
			{
				return (System.String)this.parameterstcode.Value;
			}
			set
			{
				this.parameterstcode.Value=value;
			}
		}

		public System.String BeginDate
		{
			get
			{
				return (System.String)this.parameterBeginDate.Value;
			}
			set
			{
				this.parameterBeginDate.Value=value;
			}
		}

		public System.String EndDate
		{
			get
			{
				return (System.String)this.parameterEndDate.Value;
			}
			set
			{
				this.parameterEndDate.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterstcode=new SqlParameter();
			this.parameterstcode.ParameterName="@stcode";
			this.parameterstcode.SqlDbType=SqlDbType.NVarChar;
			this.parameterstcode.Size=20;
			this.parameterstcode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterstcode);
			//--------------------------------------------------------
			this.parameterBeginDate=new SqlParameter();
			this.parameterBeginDate.ParameterName="@BeginDate";
			this.parameterBeginDate.SqlDbType=SqlDbType.NVarChar;
			this.parameterBeginDate.Size=40;
			this.parameterBeginDate.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterBeginDate);
			//--------------------------------------------------------
			this.parameterEndDate=new SqlParameter();
			this.parameterEndDate.ParameterName="@EndDate";
			this.parameterEndDate.SqlDbType=SqlDbType.NVarChar;
			this.parameterEndDate.Size=40;
			this.parameterEndDate.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterEndDate);
		}
	}
}
