//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblEQIA_R_Report_HourStat : BaseProcedure
	{
		private SqlParameter parameterBeginTime;

		private SqlParameter parameterEndTime;

		private SqlParameter parameterfldPCode;

		private SqlParameter parameterfldStandardName;

		private SqlParameter parameterfldLevel;

		private SqlParameter parameterfldItemCode;

		private SqlParameter parameterDecCarry;

		public usp_tblEQIA_R_Report_HourStat()
		{
			base.InitCommand("usp_tblEQIA_R_Report_HourStat");
			ConfigParameter();
		}

		public System.DateTime BeginTime
		{
			get
			{
				return (System.DateTime)this.parameterBeginTime.Value;
			}
			set
			{
				this.parameterBeginTime.Value=value;
			}
		}

		public System.DateTime EndTime
		{
			get
			{
				return (System.DateTime)this.parameterEndTime.Value;
			}
			set
			{
				this.parameterEndTime.Value=value;
			}
		}

		public System.String fldPCode
		{
			get
			{
				return (System.String)this.parameterfldPCode.Value;
			}
			set
			{
				this.parameterfldPCode.Value=value;
			}
		}

		public System.String fldStandardName
		{
			get
			{
				return (System.String)this.parameterfldStandardName.Value;
			}
			set
			{
				this.parameterfldStandardName.Value=value;
			}
		}

		public System.Int16 fldLevel
		{
			get
			{
				return (System.Int16)this.parameterfldLevel.Value;
			}
			set
			{
				this.parameterfldLevel.Value=value;
			}
		}

		public System.String fldItemCode
		{
			get
			{
				return (System.String)this.parameterfldItemCode.Value;
			}
			set
			{
				this.parameterfldItemCode.Value=value;
			}
		}

		public System.String DecCarry
		{
			get
			{
				return (System.String)this.parameterDecCarry.Value;
			}
			set
			{
				this.parameterDecCarry.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterBeginTime=new SqlParameter();
			this.parameterBeginTime.ParameterName="@BeginTime";
			this.parameterBeginTime.SqlDbType=SqlDbType.DateTime;
			this.parameterBeginTime.Size=8;
			this.parameterBeginTime.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterBeginTime);
			//--------------------------------------------------------
			this.parameterEndTime=new SqlParameter();
			this.parameterEndTime.ParameterName="@EndTime";
			this.parameterEndTime.SqlDbType=SqlDbType.DateTime;
			this.parameterEndTime.Size=8;
			this.parameterEndTime.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterEndTime);
			//--------------------------------------------------------
			this.parameterfldPCode=new SqlParameter();
			this.parameterfldPCode.ParameterName="@fldPCode";
			this.parameterfldPCode.SqlDbType=SqlDbType.VarChar;
			this.parameterfldPCode.Size=-1;
			this.parameterfldPCode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldPCode);
			//--------------------------------------------------------
			this.parameterfldStandardName=new SqlParameter();
			this.parameterfldStandardName.ParameterName="@fldStandardName";
			this.parameterfldStandardName.SqlDbType=SqlDbType.VarChar;
			this.parameterfldStandardName.Size=100;
			this.parameterfldStandardName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldStandardName);
			//--------------------------------------------------------
			this.parameterfldLevel=new SqlParameter();
			this.parameterfldLevel.ParameterName="@fldLevel";
			this.parameterfldLevel.SqlDbType=SqlDbType.SmallInt;
			this.parameterfldLevel.Size=2;
			this.parameterfldLevel.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldLevel);
			//--------------------------------------------------------
			this.parameterfldItemCode=new SqlParameter();
			this.parameterfldItemCode.ParameterName="@fldItemCode";
			this.parameterfldItemCode.SqlDbType=SqlDbType.VarChar;
			this.parameterfldItemCode.Size=4000;
			this.parameterfldItemCode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldItemCode);
			//--------------------------------------------------------
			this.parameterDecCarry=new SqlParameter();
			this.parameterDecCarry.ParameterName="@DecCarry";
			this.parameterDecCarry.SqlDbType=SqlDbType.VarChar;
			this.parameterDecCarry.Size=1;
			this.parameterDecCarry.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterDecCarry);
		}
	}
}
