//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblEQIA_RPI_BaseData_GetTrendAQIOrDensity_Page : BaseProcedure
	{
		private SqlParameter parameterfldSTCode;

		private SqlParameter parameterDay;

		private SqlParameter parameterType;

		public usp_tblEQIA_RPI_BaseData_GetTrendAQIOrDensity_Page()
		{
			base.InitCommand("usp_tblEQIA_RPI_BaseData_GetTrendAQIOrDensity_Page");
			ConfigParameter();
		}

		public System.String fldSTCode
		{
			get
			{
				return (System.String)this.parameterfldSTCode.Value;
			}
			set
			{
				this.parameterfldSTCode.Value=value;
			}
		}

		public System.Int32 Day
		{
			get
			{
				return (System.Int32)this.parameterDay.Value;
			}
			set
			{
				this.parameterDay.Value=value;
			}
		}

		public System.String Type
		{
			get
			{
				return (System.String)this.parameterType.Value;
			}
			set
			{
				this.parameterType.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterfldSTCode=new SqlParameter();
			this.parameterfldSTCode.ParameterName="@fldSTCode";
			this.parameterfldSTCode.SqlDbType=SqlDbType.VarChar;
			this.parameterfldSTCode.Size=50;
			this.parameterfldSTCode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldSTCode);
			//--------------------------------------------------------
			this.parameterDay=new SqlParameter();
			this.parameterDay.ParameterName="@Day";
			this.parameterDay.SqlDbType=SqlDbType.Int;
			this.parameterDay.Size=4;
			this.parameterDay.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterDay);
			//--------------------------------------------------------
			this.parameterType=new SqlParameter();
			this.parameterType.ParameterName="@Type";
			this.parameterType.SqlDbType=SqlDbType.VarChar;
			this.parameterType.Size=10;
			this.parameterType.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterType);
		}
	}
}
