//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblEQI_Point_Group_Insert : BaseProcedure
	{
		private SqlParameter parameterfldAutoID;

		private SqlParameter parameterfldObject;

		private SqlParameter parameterfldType;

		private SqlParameter parameterfldName;

		private SqlParameter parameterfldUserID;

		private SqlParameter parameterfldYear;

		private SqlParameter parameterfldPointContent;

		public usp_tblEQI_Point_Group_Insert()
		{
			base.InitCommand("usp_tblEQI_Point_Group_Insert");
			ConfigParameter();
		}

		public System.Int32 fldAutoID
		{
			get
			{
				return (System.Int32)this.parameterfldAutoID.Value;
			}
			set
			{
				this.parameterfldAutoID.Value=value;
			}
		}

		public System.String fldObject
		{
			get
			{
				return (System.String)this.parameterfldObject.Value;
			}
			set
			{
				this.parameterfldObject.Value=value;
			}
		}

		public System.Int16 fldType
		{
			get
			{
				return (System.Int16)this.parameterfldType.Value;
			}
			set
			{
				this.parameterfldType.Value=value;
			}
		}

		public System.String fldName
		{
			get
			{
				return (System.String)this.parameterfldName.Value;
			}
			set
			{
				this.parameterfldName.Value=value;
			}
		}

		public System.Int32 fldUserID
		{
			get
			{
				return (System.Int32)this.parameterfldUserID.Value;
			}
			set
			{
				this.parameterfldUserID.Value=value;
			}
		}

		public System.Decimal fldYear
		{
			get
			{
				return (System.Decimal)this.parameterfldYear.Value;
			}
			set
			{
				this.parameterfldYear.Value=value;
			}
		}

		public System.String fldPointContent
		{
			get
			{
				return (System.String)this.parameterfldPointContent.Value;
			}
			set
			{
				this.parameterfldPointContent.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterfldAutoID=new SqlParameter();
			this.parameterfldAutoID.ParameterName="@fldAutoID";
			this.parameterfldAutoID.SqlDbType=SqlDbType.Int;
			this.parameterfldAutoID.Size=4;
			this.parameterfldAutoID.Direction=ParameterDirection.InputOutput;
			base.m_cmd.Parameters.Add(this.parameterfldAutoID);
			//--------------------------------------------------------
			this.parameterfldObject=new SqlParameter();
			this.parameterfldObject.ParameterName="@fldObject";
			this.parameterfldObject.SqlDbType=SqlDbType.VarChar;
			this.parameterfldObject.Size=20;
			this.parameterfldObject.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldObject);
			//--------------------------------------------------------
			this.parameterfldType=new SqlParameter();
			this.parameterfldType.ParameterName="@fldType";
			this.parameterfldType.SqlDbType=SqlDbType.SmallInt;
			this.parameterfldType.Size=2;
			this.parameterfldType.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldType);
			//--------------------------------------------------------
			this.parameterfldName=new SqlParameter();
			this.parameterfldName.ParameterName="@fldName";
			this.parameterfldName.SqlDbType=SqlDbType.VarChar;
			this.parameterfldName.Size=100;
			this.parameterfldName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldName);
			//--------------------------------------------------------
			this.parameterfldUserID=new SqlParameter();
			this.parameterfldUserID.ParameterName="@fldUserID";
			this.parameterfldUserID.SqlDbType=SqlDbType.Int;
			this.parameterfldUserID.Size=4;
			this.parameterfldUserID.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldUserID);
			//--------------------------------------------------------
			this.parameterfldYear=new SqlParameter();
			this.parameterfldYear.ParameterName="@fldYear";
			this.parameterfldYear.SqlDbType=SqlDbType.Decimal;
			this.parameterfldYear.Size=5;
			this.parameterfldYear.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldYear);
			//--------------------------------------------------------
			this.parameterfldPointContent=new SqlParameter();
			this.parameterfldPointContent.ParameterName="@fldPointContent";
			this.parameterfldPointContent.SqlDbType=SqlDbType.VarChar;
			this.parameterfldPointContent.Size=-1;
			this.parameterfldPointContent.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldPointContent);
		}
	}
}
