//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblDictionary_GetValueByParentIDAndName : BaseProcedure
	{
		private SqlParameter parameterfldParentName;

		private SqlParameter parameterfldName;

		public usp_tblDictionary_GetValueByParentIDAndName()
		{
			base.InitCommand("usp_tblDictionary_GetValueByParentIDAndName");
			ConfigParameter();
		}

		public System.String fldParentName
		{
			get
			{
				return (System.String)this.parameterfldParentName.Value;
			}
			set
			{
				this.parameterfldParentName.Value=value;
			}
		}

		public System.String fldName
		{
			get
			{
				return (System.String)this.parameterfldName.Value;
			}
			set
			{
				this.parameterfldName.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterfldParentName=new SqlParameter();
			this.parameterfldParentName.ParameterName="@fldParentName";
			this.parameterfldParentName.SqlDbType=SqlDbType.VarChar;
			this.parameterfldParentName.Size=200;
			this.parameterfldParentName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldParentName);
			//--------------------------------------------------------
			this.parameterfldName=new SqlParameter();
			this.parameterfldName.ParameterName="@fldName";
			this.parameterfldName.SqlDbType=SqlDbType.VarChar;
			this.parameterfldName.Size=200;
			this.parameterfldName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldName);
		}
	}
}
