//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;

    public class usp_tblEQIN_A_Basedata_Pre_Insert : BaseProcedure
    {
        private SqlParameter parameterfldAutoID;

        private SqlParameter parameterfldSTCode;

        private SqlParameter parameterfldGDCODE;

        private SqlParameter parameterfldYear;

        private SqlParameter parameterfldMonth;

        private SqlParameter parameterfldDay;

        private SqlParameter parameterfldHour;

        private SqlParameter parameterfldMinute;

        private SqlParameter parameterfldTimelen;

        private SqlParameter parameterfldDN;

        private SqlParameter parameterfldNDISC;

        private SqlParameter parameterfldNSC;

        private SqlParameter parameterfldLEQA;

        private SqlParameter parameterfldL10A;

        private SqlParameter parameterfldL50A;

        private SqlParameter parameterfldL90A;

        private SqlParameter parameterfldLmax;

        private SqlParameter parameterfldLmin;

        private SqlParameter parameterfldSD;

        private SqlParameter parameterfldFlag;

        private SqlParameter parameterfldImport;

        private SqlParameter parameterfldCityID_Operate;

        private SqlParameter parameterfldCityID_Submit;

        private SqlParameter parameterfldDate_Operate;

        private SqlParameter parameterfldUserID;

        private SqlParameter parameterfldMph;

        private SqlParameter parameterfldApparatus_Type;

        private SqlParameter parameterfldApparatus_Id;

        private SqlParameter parameterfldApparatus_Grade;

        private SqlParameter parameterfldMatching_Data;

        private SqlParameter parameterfldSource;

        private SqlParameter parameterfldCalibrationVluesOn;

        private SqlParameter parameterfldCalibrationVluesEnd;

        private SqlParameter parameterfldSPressureValue;

        private SqlParameter parameterfldSPressureType;

        private SqlParameter parameterfldSPressureID;

        public usp_tblEQIN_A_Basedata_Pre_Insert()
        {
            base.InitCommand("usp_tblEQIN_A_Basedata_Pre_Insert");
            ConfigParameter();
        }

        public System.Int64 fldAutoID
        {
            get
            {
                return (System.Int64)this.parameterfldAutoID.Value;
            }
            set
            {
                this.parameterfldAutoID.Value = value;
            }
        }

        public System.String fldSTCode
        {
            get
            {
                return (System.String)this.parameterfldSTCode.Value;
            }
            set
            {
                this.parameterfldSTCode.Value = value;
            }
        }

        public System.String fldGDCODE
        {
            get
            {
                return (System.String)this.parameterfldGDCODE.Value;
            }
            set
            {
                this.parameterfldGDCODE.Value = value;
            }
        }

        public System.Decimal fldYear
        {
            get
            {
                return (System.Decimal)this.parameterfldYear.Value;
            }
            set
            {
                this.parameterfldYear.Value = value;
            }
        }

        public System.Decimal fldMonth
        {
            get
            {
                return (System.Decimal)this.parameterfldMonth.Value;
            }
            set
            {
                this.parameterfldMonth.Value = value;
            }
        }

        public System.Decimal fldDay
        {
            get
            {
                return (System.Decimal)this.parameterfldDay.Value;
            }
            set
            {
                this.parameterfldDay.Value = value;
            }
        }

        public System.Decimal fldHour
        {
            get
            {
                return (System.Decimal)this.parameterfldHour.Value;
            }
            set
            {
                this.parameterfldHour.Value = value;
            }
        }

        public System.Decimal fldMinute
        {
            get
            {
                return (System.Decimal)this.parameterfldMinute.Value;
            }
            set
            {
                this.parameterfldMinute.Value = value;
            }
        }

        public System.Int32 fldTimelen
        {
            get
            {
                return (System.Int32)this.parameterfldTimelen.Value;
            }
            set
            {
                this.parameterfldTimelen.Value = value;
            }
        }

        public System.String fldDN
        {
            get
            {
                return (System.String)this.parameterfldDN.Value;
            }
            set
            {
                this.parameterfldDN.Value = value;
            }
        }

        public System.String fldNDISC
        {
            get
            {
                return (System.String)this.parameterfldNDISC.Value;
            }
            set
            {
                this.parameterfldNDISC.Value = value;
            }
        }

        public System.String fldNSC
        {
            get
            {
                return (System.String)this.parameterfldNSC.Value;
            }
            set
            {
                this.parameterfldNSC.Value = value;
            }
        }

        public System.Decimal fldLEQA
        {
            get
            {
                return (System.Decimal)this.parameterfldLEQA.Value;
            }
            set
            {
                this.parameterfldLEQA.Value = value;
            }
        }

        public System.Decimal fldL10A
        {
            get
            {
                return (System.Decimal)this.parameterfldL10A.Value;
            }
            set
            {
                this.parameterfldL10A.Value = value;
            }
        }

        public System.Decimal fldL50A
        {
            get
            {
                return (System.Decimal)this.parameterfldL50A.Value;
            }
            set
            {
                this.parameterfldL50A.Value = value;
            }
        }

        public System.Decimal fldL90A
        {
            get
            {
                return (System.Decimal)this.parameterfldL90A.Value;
            }
            set
            {
                this.parameterfldL90A.Value = value;
            }
        }

        public System.Decimal fldLmax
        {
            get
            {
                return (System.Decimal)this.parameterfldLmax.Value;
            }
            set
            {
                this.parameterfldLmax.Value = value;
            }
        }

        public System.Decimal fldLmin
        {
            get
            {
                return (System.Decimal)this.parameterfldLmin.Value;
            }
            set
            {
                this.parameterfldLmin.Value = value;
            }
        }

        public System.Decimal fldSD
        {
            get
            {
                return (System.Decimal)this.parameterfldSD.Value;
            }
            set
            {
                this.parameterfldSD.Value = value;
            }
        }

        public System.Int16 fldFlag
        {
            get
            {
                return (System.Int16)this.parameterfldFlag.Value;
            }
            set
            {
                this.parameterfldFlag.Value = value;
            }
        }

        public System.Int16 fldImport
        {
            get
            {
                return (System.Int16)this.parameterfldImport.Value;
            }
            set
            {
                this.parameterfldImport.Value = value;
            }
        }

        public System.Int32 fldCityID_Operate
        {
            get
            {
                return (System.Int32)this.parameterfldCityID_Operate.Value;
            }
            set
            {
                this.parameterfldCityID_Operate.Value = value;
            }
        }

        public System.String fldCityID_Submit
        {
            get
            {
                return (System.String)this.parameterfldCityID_Submit.Value;
            }
            set
            {
                this.parameterfldCityID_Submit.Value = value;
            }
        }

        public System.DateTime fldDate_Operate
        {
            get
            {
                return (System.DateTime)this.parameterfldDate_Operate.Value;
            }
            set
            {
                this.parameterfldDate_Operate.Value = value;
            }
        }

        public System.Int32 fldUserID
        {
            get
            {
                return (System.Int32)this.parameterfldUserID.Value;
            }
            set
            {
                this.parameterfldUserID.Value = value;
            }
        }

        public System.Decimal fldMph
        {
            get
            {
                return (System.Decimal)this.parameterfldMph.Value;
            }
            set
            {
                this.parameterfldMph.Value = value;
            }
        }

        public System.String fldApparatus_Type
        {
            get
            {
                return (System.String)this.parameterfldApparatus_Type.Value;
            }
            set
            {
                this.parameterfldApparatus_Type.Value = value;
            }
        }

        public System.String fldApparatus_Id
        {
            get
            {
                return (System.String)this.parameterfldApparatus_Id.Value;
            }
            set
            {
                this.parameterfldApparatus_Id.Value = value;
            }
        }

        public System.Boolean fldApparatus_Grade
        {
            get
            {
                return (System.Boolean)this.parameterfldApparatus_Grade.Value;
            }
            set
            {
                this.parameterfldApparatus_Grade.Value = value;
            }
        }

        public System.Boolean fldMatching_Data
        {
            get
            {
                return (System.Boolean)this.parameterfldMatching_Data.Value;
            }
            set
            {
                this.parameterfldMatching_Data.Value = value;
            }
        }

        public System.Int16 fldSource
        {
            get
            {
                return (System.Int16)this.parameterfldSource.Value;
            }
            set
            {
                this.parameterfldSource.Value = value;
            }
        }

        public System.Decimal fldCalibrationVluesOn
        {
            get
            {
                return (System.Decimal)this.parameterfldCalibrationVluesOn.Value;
            }
            set
            {
                this.parameterfldCalibrationVluesOn.Value = value;
            }
        }

        public System.Decimal fldCalibrationVluesEnd
        {
            get
            {
                return (System.Decimal)this.parameterfldCalibrationVluesEnd.Value;
            }
            set
            {
                this.parameterfldCalibrationVluesEnd.Value = value;
            }
        }

        public System.Decimal fldSPressureValue
        {
            get
            {
                return (System.Decimal)this.parameterfldSPressureValue.Value;
            }
            set
            {
                this.parameterfldSPressureValue.Value = value;
            }
        }

        public System.String fldSPressureType
        {
            get
            {
                return (System.String)this.parameterfldSPressureType.Value;
            }
            set
            {
                this.parameterfldSPressureType.Value = value;
            }
        }

        public System.String fldSPressureID
        {
            get
            {
                return (System.String)this.parameterfldSPressureID.Value;
            }
            set
            {
                this.parameterfldSPressureID.Value = value;
            }
        }

        public void ConfigParameter()
        {
            //--------------------------------------------------------
            this.parameterfldAutoID = new SqlParameter();
            this.parameterfldAutoID.ParameterName = "@fldAutoID";
            this.parameterfldAutoID.SqlDbType = SqlDbType.BigInt;
            this.parameterfldAutoID.Size = 8;
            this.parameterfldAutoID.Direction = ParameterDirection.InputOutput;
            base.m_cmd.Parameters.Add(this.parameterfldAutoID);
            //--------------------------------------------------------
            this.parameterfldSTCode = new SqlParameter();
            this.parameterfldSTCode.ParameterName = "@fldSTCode";
            this.parameterfldSTCode.SqlDbType = SqlDbType.VarChar;
            this.parameterfldSTCode.Size = 12;
            this.parameterfldSTCode.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldSTCode);
            //--------------------------------------------------------
            this.parameterfldGDCODE = new SqlParameter();
            this.parameterfldGDCODE.ParameterName = "@fldGDCODE";
            this.parameterfldGDCODE.SqlDbType = SqlDbType.VarChar;
            this.parameterfldGDCODE.Size = 12;
            this.parameterfldGDCODE.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldGDCODE);
            //--------------------------------------------------------
            this.parameterfldYear = new SqlParameter();
            this.parameterfldYear.ParameterName = "@fldYear";
            this.parameterfldYear.SqlDbType = SqlDbType.Decimal;
            this.parameterfldYear.Size = 5;
            this.parameterfldYear.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldYear);
            //--------------------------------------------------------
            this.parameterfldMonth = new SqlParameter();
            this.parameterfldMonth.ParameterName = "@fldMonth";
            this.parameterfldMonth.SqlDbType = SqlDbType.Decimal;
            this.parameterfldMonth.Size = 5;
            this.parameterfldMonth.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldMonth);
            //--------------------------------------------------------
            this.parameterfldDay = new SqlParameter();
            this.parameterfldDay.ParameterName = "@fldDay";
            this.parameterfldDay.SqlDbType = SqlDbType.Decimal;
            this.parameterfldDay.Size = 5;
            this.parameterfldDay.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldDay);
            //--------------------------------------------------------
            this.parameterfldHour = new SqlParameter();
            this.parameterfldHour.ParameterName = "@fldHour";
            this.parameterfldHour.SqlDbType = SqlDbType.Decimal;
            this.parameterfldHour.Size = 5;
            this.parameterfldHour.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldHour);
            //--------------------------------------------------------
            this.parameterfldMinute = new SqlParameter();
            this.parameterfldMinute.ParameterName = "@fldMinute";
            this.parameterfldMinute.SqlDbType = SqlDbType.Decimal;
            this.parameterfldMinute.Size = 5;
            this.parameterfldMinute.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldMinute);
            //--------------------------------------------------------
            this.parameterfldTimelen = new SqlParameter();
            this.parameterfldTimelen.ParameterName = "@fldTimelen";
            this.parameterfldTimelen.SqlDbType = SqlDbType.Int;
            this.parameterfldTimelen.Size = 4;
            this.parameterfldTimelen.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldTimelen);
            //--------------------------------------------------------
            this.parameterfldDN = new SqlParameter();
            this.parameterfldDN.ParameterName = "@fldDN";
            this.parameterfldDN.SqlDbType = SqlDbType.VarChar;
            this.parameterfldDN.Size = 10;
            this.parameterfldDN.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldDN);
            //--------------------------------------------------------
            this.parameterfldNDISC = new SqlParameter();
            this.parameterfldNDISC.ParameterName = "@fldNDISC";
            this.parameterfldNDISC.SqlDbType = SqlDbType.VarChar;
            this.parameterfldNDISC.Size = 12;
            this.parameterfldNDISC.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldNDISC);
            //--------------------------------------------------------
            this.parameterfldNSC = new SqlParameter();
            this.parameterfldNSC.ParameterName = "@fldNSC";
            this.parameterfldNSC.SqlDbType = SqlDbType.VarChar;
            this.parameterfldNSC.Size = 12;
            this.parameterfldNSC.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldNSC);
            //--------------------------------------------------------
            this.parameterfldLEQA = new SqlParameter();
            this.parameterfldLEQA.ParameterName = "@fldLEQA";
            this.parameterfldLEQA.SqlDbType = SqlDbType.Decimal;
            this.parameterfldLEQA.Size = 5;
            this.parameterfldLEQA.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldLEQA);
            //--------------------------------------------------------
            this.parameterfldL10A = new SqlParameter();
            this.parameterfldL10A.ParameterName = "@fldL10A";
            this.parameterfldL10A.SqlDbType = SqlDbType.Decimal;
            this.parameterfldL10A.Size = 5;
            this.parameterfldL10A.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldL10A);
            //--------------------------------------------------------
            this.parameterfldL50A = new SqlParameter();
            this.parameterfldL50A.ParameterName = "@fldL50A";
            this.parameterfldL50A.SqlDbType = SqlDbType.Decimal;
            this.parameterfldL50A.Size = 5;
            this.parameterfldL50A.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldL50A);
            //--------------------------------------------------------
            this.parameterfldL90A = new SqlParameter();
            this.parameterfldL90A.ParameterName = "@fldL90A";
            this.parameterfldL90A.SqlDbType = SqlDbType.Decimal;
            this.parameterfldL90A.Size = 5;
            this.parameterfldL90A.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldL90A);
            //--------------------------------------------------------
            this.parameterfldLmax = new SqlParameter();
            this.parameterfldLmax.ParameterName = "@fldLmax";
            this.parameterfldLmax.SqlDbType = SqlDbType.Decimal;
            this.parameterfldLmax.Size = 5;
            this.parameterfldLmax.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldLmax);
            //--------------------------------------------------------
            this.parameterfldLmin = new SqlParameter();
            this.parameterfldLmin.ParameterName = "@fldLmin";
            this.parameterfldLmin.SqlDbType = SqlDbType.Decimal;
            this.parameterfldLmin.Size = 5;
            this.parameterfldLmin.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldLmin);
            //--------------------------------------------------------
            this.parameterfldSD = new SqlParameter();
            this.parameterfldSD.ParameterName = "@fldSD";
            this.parameterfldSD.SqlDbType = SqlDbType.Decimal;
            this.parameterfldSD.Size = 5;
            this.parameterfldSD.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldSD);
            //--------------------------------------------------------
            this.parameterfldFlag = new SqlParameter();
            this.parameterfldFlag.ParameterName = "@fldFlag";
            this.parameterfldFlag.SqlDbType = SqlDbType.SmallInt;
            this.parameterfldFlag.Size = 2;
            this.parameterfldFlag.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldFlag);
            //--------------------------------------------------------
            this.parameterfldImport = new SqlParameter();
            this.parameterfldImport.ParameterName = "@fldImport";
            this.parameterfldImport.SqlDbType = SqlDbType.SmallInt;
            this.parameterfldImport.Size = 2;
            this.parameterfldImport.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldImport);
            //--------------------------------------------------------
            this.parameterfldCityID_Operate = new SqlParameter();
            this.parameterfldCityID_Operate.ParameterName = "@fldCityID_Operate";
            this.parameterfldCityID_Operate.SqlDbType = SqlDbType.Int;
            this.parameterfldCityID_Operate.Size = 4;
            this.parameterfldCityID_Operate.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldCityID_Operate);
            //--------------------------------------------------------
            this.parameterfldCityID_Submit = new SqlParameter();
            this.parameterfldCityID_Submit.ParameterName = "@fldCityID_Submit";
            this.parameterfldCityID_Submit.SqlDbType = SqlDbType.VarChar;
            this.parameterfldCityID_Submit.Size = 100;
            this.parameterfldCityID_Submit.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldCityID_Submit);
            //--------------------------------------------------------
            this.parameterfldDate_Operate = new SqlParameter();
            this.parameterfldDate_Operate.ParameterName = "@fldDate_Operate";
            this.parameterfldDate_Operate.SqlDbType = SqlDbType.DateTime;
            this.parameterfldDate_Operate.Size = 8;
            this.parameterfldDate_Operate.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldDate_Operate);
            //--------------------------------------------------------
            this.parameterfldUserID = new SqlParameter();
            this.parameterfldUserID.ParameterName = "@fldUserID";
            this.parameterfldUserID.SqlDbType = SqlDbType.Int;
            this.parameterfldUserID.Size = 4;
            this.parameterfldUserID.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldUserID);
            //--------------------------------------------------------
            this.parameterfldMph = new SqlParameter();
            this.parameterfldMph.ParameterName = "@fldMph";
            this.parameterfldMph.SqlDbType = SqlDbType.Decimal;
            this.parameterfldMph.Size = 5;
            this.parameterfldMph.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldMph);
            //--------------------------------------------------------
            this.parameterfldApparatus_Type = new SqlParameter();
            this.parameterfldApparatus_Type.ParameterName = "@fldApparatus_Type";
            this.parameterfldApparatus_Type.SqlDbType = SqlDbType.VarChar;
            this.parameterfldApparatus_Type.Size = 50;
            this.parameterfldApparatus_Type.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldApparatus_Type);
            //--------------------------------------------------------
            this.parameterfldApparatus_Id = new SqlParameter();
            this.parameterfldApparatus_Id.ParameterName = "@fldApparatus_Id";
            this.parameterfldApparatus_Id.SqlDbType = SqlDbType.VarChar;
            this.parameterfldApparatus_Id.Size = 50;
            this.parameterfldApparatus_Id.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldApparatus_Id);
            //--------------------------------------------------------
            this.parameterfldApparatus_Grade = new SqlParameter();
            this.parameterfldApparatus_Grade.ParameterName = "@fldApparatus_Grade";
            this.parameterfldApparatus_Grade.SqlDbType = SqlDbType.Bit;
            this.parameterfldApparatus_Grade.Size = 1;
            this.parameterfldApparatus_Grade.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldApparatus_Grade);
            //--------------------------------------------------------
            this.parameterfldMatching_Data = new SqlParameter();
            this.parameterfldMatching_Data.ParameterName = "@fldMatching_Data";
            this.parameterfldMatching_Data.SqlDbType = SqlDbType.Bit;
            this.parameterfldMatching_Data.Size = 1;
            this.parameterfldMatching_Data.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldMatching_Data);
            //--------------------------------------------------------
            this.parameterfldSource = new SqlParameter();
            this.parameterfldSource.ParameterName = "@fldSource";
            this.parameterfldSource.SqlDbType = SqlDbType.SmallInt;
            this.parameterfldSource.Size = 2;
            this.parameterfldSource.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldSource);
            //--------------------------------------------------------
            this.parameterfldCalibrationVluesOn = new SqlParameter();
            this.parameterfldCalibrationVluesOn.ParameterName = "@fldCalibrationVluesOn";
            this.parameterfldCalibrationVluesOn.SqlDbType = SqlDbType.Decimal;
            this.parameterfldCalibrationVluesOn.Size = 5;
            this.parameterfldCalibrationVluesOn.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldCalibrationVluesOn);
            //--------------------------------------------------------
            this.parameterfldCalibrationVluesEnd = new SqlParameter();
            this.parameterfldCalibrationVluesEnd.ParameterName = "@fldCalibrationVluesEnd";
            this.parameterfldCalibrationVluesEnd.SqlDbType = SqlDbType.Decimal;
            this.parameterfldCalibrationVluesEnd.Size = 5;
            this.parameterfldCalibrationVluesEnd.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldCalibrationVluesEnd);
            //--------------------------------------------------------
            this.parameterfldSPressureValue = new SqlParameter();
            this.parameterfldSPressureValue.ParameterName = "@fldSPressureValue";
            this.parameterfldSPressureValue.SqlDbType = SqlDbType.Decimal;
            this.parameterfldSPressureValue.Size = 5;
            this.parameterfldSPressureValue.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldSPressureValue);
            //--------------------------------------------------------
            this.parameterfldSPressureType = new SqlParameter();
            this.parameterfldSPressureType.ParameterName = "@fldSPressureType";
            this.parameterfldSPressureType.SqlDbType = SqlDbType.VarChar;
            this.parameterfldSPressureType.Size = 50;
            this.parameterfldSPressureType.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldSPressureType);
            //--------------------------------------------------------
            this.parameterfldSPressureID = new SqlParameter();
            this.parameterfldSPressureID.ParameterName = "@fldSPressureID";
            this.parameterfldSPressureID.SqlDbType = SqlDbType.VarChar;
            this.parameterfldSPressureID.Size = 50;
            this.parameterfldSPressureID.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldSPressureID);
        }
    }
}
