//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;

    public class usp_tblEQI_GetByType : BaseProcedure
    {
        private SqlParameter parametertype;

        private SqlParameter parameterautoid;

        public usp_tblEQI_GetByType()
        {
            base.InitCommand("usp_tblEQI_GetByType");
            ConfigParameter();
        }

        public System.String type
        {
            get
            {
                return (System.String)this.parametertype.Value;
            }
            set
            {
                this.parametertype.Value = value;
            }
        }

        public System.Int64 autoid
        {
            get
            {
                return (System.Int64)this.parameterautoid.Value;
            }
            set
            {
                this.parameterautoid.Value = value;
            }
        }

        public void ConfigParameter()
        {
            //--------------------------------------------------------
            this.parametertype = new SqlParameter();
            this.parametertype.ParameterName = "@type";
            this.parametertype.SqlDbType = SqlDbType.VarChar;
            this.parametertype.Size = 50;
            this.parametertype.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parametertype);
            //--------------------------------------------------------
            this.parameterautoid = new SqlParameter();
            this.parameterautoid.ParameterName = "@autoid";
            this.parameterautoid.SqlDbType = SqlDbType.BigInt;
            this.parameterautoid.Size = 8;
            this.parameterautoid.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterautoid);
        }
    }
}
