//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;

    public class usp_tblEQIA_PPI_BaseData_Insert : BaseProcedure
    {
        private SqlParameter parameterfldAutoID;

        private SqlParameter parameterfldSTCode;

        private SqlParameter parameterfldSTName;

        private SqlParameter parameterfldPCode;

        private SqlParameter parameterfldPName;

        private SqlParameter parameterfldType;

        private SqlParameter parameterfldSYear;

        private SqlParameter parameterfldSMonth;

        private SqlParameter parameterfldSDay;

        private SqlParameter parameterfldSHour;

        private SqlParameter parameterfldSMinute;

        private SqlParameter parameterfldEYear;

        private SqlParameter parameterfldEMonth;

        private SqlParameter parameterfldEDay;

        private SqlParameter parameterfldEHour;

        private SqlParameter parameterfldEMinute;

        private SqlParameter parameterfldItemCode;

        private SqlParameter parameterfldItemName;

        private SqlParameter parameterfldItemValue;

        private SqlParameter parameterfldBReport;

        private SqlParameter parameterfldUserID;

        public usp_tblEQIA_PPI_BaseData_Insert()
        {
            base.InitCommand("usp_tblEQIA_PPI_BaseData_Insert");
            ConfigParameter();
        }

        public System.Int64 fldAutoID
        {
            get
            {
                return (System.Int64)this.parameterfldAutoID.Value;
            }
            set
            {
                this.parameterfldAutoID.Value = value;
            }
        }

        public System.String fldSTCode
        {
            get
            {
                return (System.String)this.parameterfldSTCode.Value;
            }
            set
            {
                this.parameterfldSTCode.Value = value;
            }
        }

        public System.String fldSTName
        {
            get
            {
                return (System.String)this.parameterfldSTName.Value;
            }
            set
            {
                this.parameterfldSTName.Value = value;
            }
        }

        public System.String fldPCode
        {
            get
            {
                return (System.String)this.parameterfldPCode.Value;
            }
            set
            {
                this.parameterfldPCode.Value = value;
            }
        }

        public System.String fldPName
        {
            get
            {
                return (System.String)this.parameterfldPName.Value;
            }
            set
            {
                this.parameterfldPName.Value = value;
            }
        }

        public System.Int16 fldType
        {
            get
            {
                return (System.Int16)this.parameterfldType.Value;
            }
            set
            {
                this.parameterfldType.Value = value;
            }
        }

        public System.Decimal fldSYear
        {
            get
            {
                return (System.Decimal)this.parameterfldSYear.Value;
            }
            set
            {
                this.parameterfldSYear.Value = value;
            }
        }

        public System.Decimal fldSMonth
        {
            get
            {
                return (System.Decimal)this.parameterfldSMonth.Value;
            }
            set
            {
                this.parameterfldSMonth.Value = value;
            }
        }

        public System.Decimal fldSDay
        {
            get
            {
                return (System.Decimal)this.parameterfldSDay.Value;
            }
            set
            {
                this.parameterfldSDay.Value = value;
            }
        }

        public System.Decimal fldSHour
        {
            get
            {
                return (System.Decimal)this.parameterfldSHour.Value;
            }
            set
            {
                this.parameterfldSHour.Value = value;
            }
        }

        public System.Decimal fldSMinute
        {
            get
            {
                return (System.Decimal)this.parameterfldSMinute.Value;
            }
            set
            {
                this.parameterfldSMinute.Value = value;
            }
        }

        public System.Decimal fldEYear
        {
            get
            {
                return (System.Decimal)this.parameterfldEYear.Value;
            }
            set
            {
                this.parameterfldEYear.Value = value;
            }
        }

        public System.Decimal fldEMonth
        {
            get
            {
                return (System.Decimal)this.parameterfldEMonth.Value;
            }
            set
            {
                this.parameterfldEMonth.Value = value;
            }
        }

        public System.Decimal fldEDay
        {
            get
            {
                return (System.Decimal)this.parameterfldEDay.Value;
            }
            set
            {
                this.parameterfldEDay.Value = value;
            }
        }

        public System.Decimal fldEHour
        {
            get
            {
                return (System.Decimal)this.parameterfldEHour.Value;
            }
            set
            {
                this.parameterfldEHour.Value = value;
            }
        }

        public System.Decimal fldEMinute
        {
            get
            {
                return (System.Decimal)this.parameterfldEMinute.Value;
            }
            set
            {
                this.parameterfldEMinute.Value = value;
            }
        }

        public System.String fldItemCode
        {
            get
            {
                return (System.String)this.parameterfldItemCode.Value;
            }
            set
            {
                this.parameterfldItemCode.Value = value;
            }
        }

        public System.String fldItemName
        {
            get
            {
                return (System.String)this.parameterfldItemName.Value;
            }
            set
            {
                this.parameterfldItemName.Value = value;
            }
        }

        public System.Decimal fldItemValue
        {
            get
            {
                return (System.Decimal)this.parameterfldItemValue.Value;
            }
            set
            {
                this.parameterfldItemValue.Value = value;
            }
        }

        public System.Boolean fldBReport
        {
            get
            {
                return (System.Boolean)this.parameterfldBReport.Value;
            }
            set
            {
                this.parameterfldBReport.Value = value;
            }
        }

        public System.Int32 fldUserID
        {
            get
            {
                return (System.Int32)this.parameterfldUserID.Value;
            }
            set
            {
                this.parameterfldUserID.Value = value;
            }
        }

        public void ConfigParameter()
        {
            //--------------------------------------------------------
            this.parameterfldAutoID = new SqlParameter();
            this.parameterfldAutoID.ParameterName = "@fldAutoID";
            this.parameterfldAutoID.SqlDbType = SqlDbType.BigInt;
            this.parameterfldAutoID.Size = 8;
            this.parameterfldAutoID.Direction = ParameterDirection.InputOutput;
            base.m_cmd.Parameters.Add(this.parameterfldAutoID);
            //--------------------------------------------------------
            this.parameterfldSTCode = new SqlParameter();
            this.parameterfldSTCode.ParameterName = "@fldSTCode";
            this.parameterfldSTCode.SqlDbType = SqlDbType.VarChar;
            this.parameterfldSTCode.Size = 12;
            this.parameterfldSTCode.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldSTCode);
            //--------------------------------------------------------
            this.parameterfldSTName = new SqlParameter();
            this.parameterfldSTName.ParameterName = "@fldSTName";
            this.parameterfldSTName.SqlDbType = SqlDbType.VarChar;
            this.parameterfldSTName.Size = 30;
            this.parameterfldSTName.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldSTName);
            //--------------------------------------------------------
            this.parameterfldPCode = new SqlParameter();
            this.parameterfldPCode.ParameterName = "@fldPCode";
            this.parameterfldPCode.SqlDbType = SqlDbType.VarChar;
            this.parameterfldPCode.Size = 12;
            this.parameterfldPCode.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldPCode);
            //--------------------------------------------------------
            this.parameterfldPName = new SqlParameter();
            this.parameterfldPName.ParameterName = "@fldPName";
            this.parameterfldPName.SqlDbType = SqlDbType.VarChar;
            this.parameterfldPName.Size = 100;
            this.parameterfldPName.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldPName);
            //--------------------------------------------------------
            this.parameterfldType = new SqlParameter();
            this.parameterfldType.ParameterName = "@fldType";
            this.parameterfldType.SqlDbType = SqlDbType.SmallInt;
            this.parameterfldType.Size = 2;
            this.parameterfldType.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldType);
            //--------------------------------------------------------
            this.parameterfldSYear = new SqlParameter();
            this.parameterfldSYear.ParameterName = "@fldSYear";
            this.parameterfldSYear.SqlDbType = SqlDbType.Decimal;
            this.parameterfldSYear.Size = 5;
            this.parameterfldSYear.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldSYear);
            //--------------------------------------------------------
            this.parameterfldSMonth = new SqlParameter();
            this.parameterfldSMonth.ParameterName = "@fldSMonth";
            this.parameterfldSMonth.SqlDbType = SqlDbType.Decimal;
            this.parameterfldSMonth.Size = 5;
            this.parameterfldSMonth.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldSMonth);
            //--------------------------------------------------------
            this.parameterfldSDay = new SqlParameter();
            this.parameterfldSDay.ParameterName = "@fldSDay";
            this.parameterfldSDay.SqlDbType = SqlDbType.Decimal;
            this.parameterfldSDay.Size = 5;
            this.parameterfldSDay.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldSDay);
            //--------------------------------------------------------
            this.parameterfldSHour = new SqlParameter();
            this.parameterfldSHour.ParameterName = "@fldSHour";
            this.parameterfldSHour.SqlDbType = SqlDbType.Decimal;
            this.parameterfldSHour.Size = 5;
            this.parameterfldSHour.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldSHour);
            //--------------------------------------------------------
            this.parameterfldSMinute = new SqlParameter();
            this.parameterfldSMinute.ParameterName = "@fldSMinute";
            this.parameterfldSMinute.SqlDbType = SqlDbType.Decimal;
            this.parameterfldSMinute.Size = 5;
            this.parameterfldSMinute.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldSMinute);
            //--------------------------------------------------------
            this.parameterfldEYear = new SqlParameter();
            this.parameterfldEYear.ParameterName = "@fldEYear";
            this.parameterfldEYear.SqlDbType = SqlDbType.Decimal;
            this.parameterfldEYear.Size = 5;
            this.parameterfldEYear.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldEYear);
            //--------------------------------------------------------
            this.parameterfldEMonth = new SqlParameter();
            this.parameterfldEMonth.ParameterName = "@fldEMonth";
            this.parameterfldEMonth.SqlDbType = SqlDbType.Decimal;
            this.parameterfldEMonth.Size = 5;
            this.parameterfldEMonth.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldEMonth);
            //--------------------------------------------------------
            this.parameterfldEDay = new SqlParameter();
            this.parameterfldEDay.ParameterName = "@fldEDay";
            this.parameterfldEDay.SqlDbType = SqlDbType.Decimal;
            this.parameterfldEDay.Size = 5;
            this.parameterfldEDay.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldEDay);
            //--------------------------------------------------------
            this.parameterfldEHour = new SqlParameter();
            this.parameterfldEHour.ParameterName = "@fldEHour";
            this.parameterfldEHour.SqlDbType = SqlDbType.Decimal;
            this.parameterfldEHour.Size = 5;
            this.parameterfldEHour.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldEHour);
            //--------------------------------------------------------
            this.parameterfldEMinute = new SqlParameter();
            this.parameterfldEMinute.ParameterName = "@fldEMinute";
            this.parameterfldEMinute.SqlDbType = SqlDbType.Decimal;
            this.parameterfldEMinute.Size = 5;
            this.parameterfldEMinute.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldEMinute);
            //--------------------------------------------------------
            this.parameterfldItemCode = new SqlParameter();
            this.parameterfldItemCode.ParameterName = "@fldItemCode";
            this.parameterfldItemCode.SqlDbType = SqlDbType.VarChar;
            this.parameterfldItemCode.Size = 10;
            this.parameterfldItemCode.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldItemCode);
            //--------------------------------------------------------
            this.parameterfldItemName = new SqlParameter();
            this.parameterfldItemName.ParameterName = "@fldItemName";
            this.parameterfldItemName.SqlDbType = SqlDbType.VarChar;
            this.parameterfldItemName.Size = 50;
            this.parameterfldItemName.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldItemName);
            //--------------------------------------------------------
            this.parameterfldItemValue = new SqlParameter();
            this.parameterfldItemValue.ParameterName = "@fldItemValue";
            this.parameterfldItemValue.SqlDbType = SqlDbType.Decimal;
            this.parameterfldItemValue.Size = 17;
            this.parameterfldItemValue.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldItemValue);
            //--------------------------------------------------------
            this.parameterfldBReport = new SqlParameter();
            this.parameterfldBReport.ParameterName = "@fldBReport";
            this.parameterfldBReport.SqlDbType = SqlDbType.Bit;
            this.parameterfldBReport.Size = 1;
            this.parameterfldBReport.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldBReport);
            //--------------------------------------------------------
            this.parameterfldUserID = new SqlParameter();
            this.parameterfldUserID.ParameterName = "@fldUserID";
            this.parameterfldUserID.SqlDbType = SqlDbType.Int;
            this.parameterfldUserID.Size = 4;
            this.parameterfldUserID.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldUserID);
        }
    }
}
