//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblEQI_Item_Group_Insert : BaseProcedure
	{
		private SqlParameter parameterfldAutoID;

		private SqlParameter parameterfldObject;

		private SqlParameter parameterfldName;

		private SqlParameter parameterfldUserID;

		private SqlParameter parameterfldItemContent;

		public usp_tblEQI_Item_Group_Insert()
		{
			base.InitCommand("usp_tblEQI_Item_Group_Insert");
			ConfigParameter();
		}

		public System.Int32 fldAutoID
		{
			get
			{
				return (System.Int32)this.parameterfldAutoID.Value;
			}
			set
			{
				this.parameterfldAutoID.Value=value;
			}
		}

		public System.String fldObject
		{
			get
			{
				return (System.String)this.parameterfldObject.Value;
			}
			set
			{
				this.parameterfldObject.Value=value;
			}
		}

		public System.String fldName
		{
			get
			{
				return (System.String)this.parameterfldName.Value;
			}
			set
			{
				this.parameterfldName.Value=value;
			}
		}

		public System.Int32 fldUserID
		{
			get
			{
				return (System.Int32)this.parameterfldUserID.Value;
			}
			set
			{
				this.parameterfldUserID.Value=value;
			}
		}

		public System.String fldItemContent
		{
			get
			{
				return (System.String)this.parameterfldItemContent.Value;
			}
			set
			{
				this.parameterfldItemContent.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterfldAutoID=new SqlParameter();
			this.parameterfldAutoID.ParameterName="@fldAutoID";
			this.parameterfldAutoID.SqlDbType=SqlDbType.Int;
			this.parameterfldAutoID.Size=4;
			this.parameterfldAutoID.Direction=ParameterDirection.InputOutput;
			base.m_cmd.Parameters.Add(this.parameterfldAutoID);
			//--------------------------------------------------------
			this.parameterfldObject=new SqlParameter();
			this.parameterfldObject.ParameterName="@fldObject";
			this.parameterfldObject.SqlDbType=SqlDbType.VarChar;
			this.parameterfldObject.Size=20;
			this.parameterfldObject.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldObject);
			//--------------------------------------------------------
			this.parameterfldName=new SqlParameter();
			this.parameterfldName.ParameterName="@fldName";
			this.parameterfldName.SqlDbType=SqlDbType.VarChar;
			this.parameterfldName.Size=100;
			this.parameterfldName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldName);
			//--------------------------------------------------------
			this.parameterfldUserID=new SqlParameter();
			this.parameterfldUserID.ParameterName="@fldUserID";
			this.parameterfldUserID.SqlDbType=SqlDbType.Int;
			this.parameterfldUserID.Size=4;
			this.parameterfldUserID.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldUserID);
			//--------------------------------------------------------
			this.parameterfldItemContent=new SqlParameter();
			this.parameterfldItemContent.ParameterName="@fldItemContent";
			this.parameterfldItemContent.SqlDbType=SqlDbType.VarChar;
			this.parameterfldItemContent.Size=3000;
			this.parameterfldItemContent.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldItemContent);
		}
	}
}
