//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_Dictionaries : BaseProcedure
	{
		private SqlParameter parameterOutChar;

		private SqlParameter parameterChannelName;

		private SqlParameter parameterBankName;


        public usp_Dictionaries()
		{
			base.InitCommand("usp_Dictionaries");
			ConfigParameter();
		}

		public System.String OutChar
        {
			get
			{
				return (System.String)this.parameterOutChar.Value;
			}
			set
			{
				this.parameterOutChar.Value=value;
			}
		}

		public System.String ChannelName
        {
			get
			{
				return (System.String)this.parameterChannelName.Value;
			}
			set
			{
				this.parameterChannelName.Value=value;
			}
		}

		public System.String BankName
        {
			get
			{
				return (System.String)this.parameterBankName.Value;
			}
			set
			{
				this.parameterBankName.Value=value;
			}
		}

        public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterOutChar = new SqlParameter();
			this.parameterOutChar.ParameterName= "@OutChar";
			this.parameterOutChar.SqlDbType=SqlDbType.VarChar;
			this.parameterOutChar.Size=500;
			this.parameterOutChar.Direction=ParameterDirection.Output;
			base.m_cmd.Parameters.Add(this.parameterOutChar);
			//--------------------------------------------------------
			this.parameterChannelName = new SqlParameter();
			this.parameterChannelName.ParameterName= "@ChannelName";
			this.parameterChannelName.SqlDbType=SqlDbType.VarChar;
            this.parameterChannelName.Size = 500;
			this.parameterChannelName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterChannelName);
			//--------------------------------------------------------
			this.parameterBankName = new SqlParameter();
			this.parameterBankName.ParameterName= "@BankName";
			this.parameterBankName.SqlDbType=SqlDbType.VarChar;
			this.parameterBankName.Size=500;
			this.parameterBankName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterBankName);
         
        }
	}
}
