//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;

    public class usp_updatetblAgentPayfail : BaseProcedure
    {
        private SqlParameter parameterfldMerchID;

        private SqlParameter parameterfldChannelnum;

        private SqlParameter parameterfldStaute;

        private SqlParameter parameterfldTotalAmount;

        private SqlParameter parameterIsSuccess;

        public usp_updatetblAgentPayfail()
        {
            base.InitCommand("usp_updatetblAgentPayfail");
            ConfigParameter();
        }

        public System.String fldMerchID
        {
            get
            {
                return (System.String)this.parameterfldMerchID.Value;
            }
            set
            {
                this.parameterfldMerchID.Value = value;
            }
        }

        public System.String fldChannelnum
        {
            get
            {
                return (System.String)this.parameterfldChannelnum.Value;
            }
            set
            {
                this.parameterfldChannelnum.Value = value;
            }
        }

        public System.String fldStaute
        {
            get
            {
                return (System.String)this.parameterfldStaute.Value;
            }
            set
            {
                this.parameterfldStaute.Value = value;
            }
        }

        public System.Decimal fldTotalAmount
        {
            get
            {
                return (System.Decimal)this.parameterfldTotalAmount.Value;
            }
            set
            {
                this.parameterfldTotalAmount.Value = value;
            }
        }

        public System.Boolean IsSuccess
        {
            get
            {
                return (System.Boolean)this.parameterIsSuccess.Value;
            }
            set
            {
                this.parameterIsSuccess.Value = value;
            }
        }

        public void ConfigParameter()
        {
            //--------------------------------------------------------
            this.parameterfldMerchID = new SqlParameter();
            this.parameterfldMerchID.ParameterName = "@fldMerchID";
            this.parameterfldMerchID.SqlDbType = SqlDbType.VarChar;
            this.parameterfldMerchID.Size = 50;
            this.parameterfldMerchID.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldMerchID);
            //--------------------------------------------------------
            this.parameterfldChannelnum = new SqlParameter();
            this.parameterfldChannelnum.ParameterName = "@fldChannelnum";
            this.parameterfldChannelnum.SqlDbType = SqlDbType.VarChar;
            this.parameterfldChannelnum.Size = 50;
            this.parameterfldChannelnum.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldChannelnum);
            //--------------------------------------------------------
            this.parameterfldStaute = new SqlParameter();
            this.parameterfldStaute.ParameterName = "@fldStaute";
            this.parameterfldStaute.SqlDbType = SqlDbType.VarChar;
            this.parameterfldStaute.Size = 50;
            this.parameterfldStaute.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldStaute);
            //--------------------------------------------------------
            this.parameterfldTotalAmount = new SqlParameter();
            this.parameterfldTotalAmount.ParameterName = "@fldTotalAmount";
            this.parameterfldTotalAmount.SqlDbType = SqlDbType.Decimal;
            this.parameterfldTotalAmount.Size = 17;
            this.parameterfldTotalAmount.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldTotalAmount);
            //--------------------------------------------------------
            this.parameterIsSuccess = new SqlParameter();
            this.parameterIsSuccess.ParameterName = "@IsSuccess";
            this.parameterIsSuccess.SqlDbType = SqlDbType.Bit;
            this.parameterIsSuccess.Size = 2;
            this.parameterIsSuccess.Direction = ParameterDirection.Output;
            base.m_cmd.Parameters.Add(this.parameterIsSuccess);
        }
    }
}
