//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblEQISE_Item_Insert : BaseProcedure
	{
		private SqlParameter parameterfldAutoID;

		private SqlParameter parameterfldItemCode;

		private SqlParameter parameterfldItemName;

		private SqlParameter parameterfldCharCode;

		private SqlParameter parameterfldChineseCode;

		private SqlParameter parameterfldUnit;

		private SqlParameter parameterfldInt;

		private SqlParameter parameterfldDec;

		private SqlParameter parameterfldMinValue;

		private SqlParameter parameterfldMaxValue;

		private SqlParameter parameterfldAnalyseWay;

		private SqlParameter parameterfldSense;

		private SqlParameter parameterfldWayOrigin;

		private SqlParameter parameterfldSort;

		public usp_tblEQISE_Item_Insert()
		{
			base.InitCommand("usp_tblEQISE_Item_Insert");
			ConfigParameter();
		}

		public System.Int32 fldAutoID
		{
			get
			{
				return (System.Int32)this.parameterfldAutoID.Value;
			}
			set
			{
				this.parameterfldAutoID.Value=value;
			}
		}

		public System.String fldItemCode
		{
			get
			{
				return (System.String)this.parameterfldItemCode.Value;
			}
			set
			{
				this.parameterfldItemCode.Value=value;
			}
		}

		public System.String fldItemName
		{
			get
			{
				return (System.String)this.parameterfldItemName.Value;
			}
			set
			{
				this.parameterfldItemName.Value=value;
			}
		}

		public System.String fldCharCode
		{
			get
			{
				return (System.String)this.parameterfldCharCode.Value;
			}
			set
			{
				this.parameterfldCharCode.Value=value;
			}
		}

		public System.String fldChineseCode
		{
			get
			{
				return (System.String)this.parameterfldChineseCode.Value;
			}
			set
			{
				this.parameterfldChineseCode.Value=value;
			}
		}

		public System.String fldUnit
		{
			get
			{
				return (System.String)this.parameterfldUnit.Value;
			}
			set
			{
				this.parameterfldUnit.Value=value;
			}
		}

		public System.Decimal fldInt
		{
			get
			{
				return (System.Decimal)this.parameterfldInt.Value;
			}
			set
			{
				this.parameterfldInt.Value=value;
			}
		}

		public System.Decimal fldDec
		{
			get
			{
				return (System.Decimal)this.parameterfldDec.Value;
			}
			set
			{
				this.parameterfldDec.Value=value;
			}
		}

		public System.Decimal fldMinValue
		{
			get
			{
				return (System.Decimal)this.parameterfldMinValue.Value;
			}
			set
			{
				this.parameterfldMinValue.Value=value;
			}
		}

		public System.Decimal fldMaxValue
		{
			get
			{
				return (System.Decimal)this.parameterfldMaxValue.Value;
			}
			set
			{
				this.parameterfldMaxValue.Value=value;
			}
		}

		public System.String fldAnalyseWay
		{
			get
			{
				return (System.String)this.parameterfldAnalyseWay.Value;
			}
			set
			{
				this.parameterfldAnalyseWay.Value=value;
			}
		}

		public System.Decimal fldSense
		{
			get
			{
				return (System.Decimal)this.parameterfldSense.Value;
			}
			set
			{
				this.parameterfldSense.Value=value;
			}
		}

		public System.String fldWayOrigin
		{
			get
			{
				return (System.String)this.parameterfldWayOrigin.Value;
			}
			set
			{
				this.parameterfldWayOrigin.Value=value;
			}
		}

		public System.Int16 fldSort
		{
			get
			{
				return (System.Int16)this.parameterfldSort.Value;
			}
			set
			{
				this.parameterfldSort.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterfldAutoID=new SqlParameter();
			this.parameterfldAutoID.ParameterName="@fldAutoID";
			this.parameterfldAutoID.SqlDbType=SqlDbType.Int;
			this.parameterfldAutoID.Size=4;
			this.parameterfldAutoID.Direction=ParameterDirection.InputOutput;
			base.m_cmd.Parameters.Add(this.parameterfldAutoID);
			//--------------------------------------------------------
			this.parameterfldItemCode=new SqlParameter();
			this.parameterfldItemCode.ParameterName="@fldItemCode";
			this.parameterfldItemCode.SqlDbType=SqlDbType.VarChar;
			this.parameterfldItemCode.Size=10;
			this.parameterfldItemCode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldItemCode);
			//--------------------------------------------------------
			this.parameterfldItemName=new SqlParameter();
			this.parameterfldItemName.ParameterName="@fldItemName";
			this.parameterfldItemName.SqlDbType=SqlDbType.VarChar;
			this.parameterfldItemName.Size=50;
			this.parameterfldItemName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldItemName);
			//--------------------------------------------------------
			this.parameterfldCharCode=new SqlParameter();
			this.parameterfldCharCode.ParameterName="@fldCharCode";
			this.parameterfldCharCode.SqlDbType=SqlDbType.VarChar;
			this.parameterfldCharCode.Size=10;
			this.parameterfldCharCode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldCharCode);
			//--------------------------------------------------------
			this.parameterfldChineseCode=new SqlParameter();
			this.parameterfldChineseCode.ParameterName="@fldChineseCode";
			this.parameterfldChineseCode.SqlDbType=SqlDbType.VarChar;
			this.parameterfldChineseCode.Size=20;
			this.parameterfldChineseCode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldChineseCode);
			//--------------------------------------------------------
			this.parameterfldUnit=new SqlParameter();
			this.parameterfldUnit.ParameterName="@fldUnit";
			this.parameterfldUnit.SqlDbType=SqlDbType.VarChar;
			this.parameterfldUnit.Size=25;
			this.parameterfldUnit.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldUnit);
			//--------------------------------------------------------
			this.parameterfldInt=new SqlParameter();
			this.parameterfldInt.ParameterName="@fldInt";
			this.parameterfldInt.SqlDbType=SqlDbType.Decimal;
			this.parameterfldInt.Size=5;
			this.parameterfldInt.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldInt);
			//--------------------------------------------------------
			this.parameterfldDec=new SqlParameter();
			this.parameterfldDec.ParameterName="@fldDec";
			this.parameterfldDec.SqlDbType=SqlDbType.Decimal;
			this.parameterfldDec.Size=5;
			this.parameterfldDec.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldDec);
			//--------------------------------------------------------
			this.parameterfldMinValue=new SqlParameter();
			this.parameterfldMinValue.ParameterName="@fldMinValue";
			this.parameterfldMinValue.SqlDbType=SqlDbType.Decimal;
			this.parameterfldMinValue.Size=17;
			this.parameterfldMinValue.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldMinValue);
			//--------------------------------------------------------
			this.parameterfldMaxValue=new SqlParameter();
			this.parameterfldMaxValue.ParameterName="@fldMaxValue";
			this.parameterfldMaxValue.SqlDbType=SqlDbType.Decimal;
			this.parameterfldMaxValue.Size=17;
			this.parameterfldMaxValue.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldMaxValue);
			//--------------------------------------------------------
			this.parameterfldAnalyseWay=new SqlParameter();
			this.parameterfldAnalyseWay.ParameterName="@fldAnalyseWay";
			this.parameterfldAnalyseWay.SqlDbType=SqlDbType.VarChar;
			this.parameterfldAnalyseWay.Size=200;
			this.parameterfldAnalyseWay.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldAnalyseWay);
			//--------------------------------------------------------
			this.parameterfldSense=new SqlParameter();
			this.parameterfldSense.ParameterName="@fldSense";
			this.parameterfldSense.SqlDbType=SqlDbType.Decimal;
			this.parameterfldSense.Size=17;
			this.parameterfldSense.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldSense);
			//--------------------------------------------------------
			this.parameterfldWayOrigin=new SqlParameter();
			this.parameterfldWayOrigin.ParameterName="@fldWayOrigin";
			this.parameterfldWayOrigin.SqlDbType=SqlDbType.VarChar;
			this.parameterfldWayOrigin.Size=60;
			this.parameterfldWayOrigin.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldWayOrigin);
			//--------------------------------------------------------
			this.parameterfldSort=new SqlParameter();
			this.parameterfldSort.ParameterName="@fldSort";
			this.parameterfldSort.SqlDbType=SqlDbType.SmallInt;
			this.parameterfldSort.Size=2;
			this.parameterfldSort.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldSort);
		}
	}
}
