//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblEQIW_R_Section_ByRiverSystemType : BaseProcedure
	{
		private SqlParameter parameterfldType;

		private SqlParameter parameterfldYear;

		public usp_tblEQIW_R_Section_ByRiverSystemType()
		{
			base.InitCommand("usp_tblEQIW_R_Section_ByRiverSystemType");
			ConfigParameter();
		}

		public System.String fldType
		{
			get
			{
				return (System.String)this.parameterfldType.Value;
			}
			set
			{
				this.parameterfldType.Value=value;
			}
		}

        public System.Int32 fldYear
		{
			get
			{
                return (System.Int32)this.parameterfldYear.Value;
			}
			set
			{
                this.parameterfldYear.Value = value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterfldType=new SqlParameter();
			this.parameterfldType.ParameterName="@fldType";
			this.parameterfldType.SqlDbType=SqlDbType.VarChar;
			this.parameterfldType.Size=20;
			this.parameterfldType.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldType);
			//--------------------------------------------------------
            this.parameterfldYear = new SqlParameter();
            this.parameterfldYear.ParameterName = "@fldYear";
            this.parameterfldYear.SqlDbType = SqlDbType.Int;
            this.parameterfldYear.Size = 8;
            this.parameterfldYear.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldYear);
		}
	}
}
