//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_GetField : BaseProcedure
	{
		private SqlParameter parameterfield;

		private SqlParameter parameterTableName;

		private SqlParameter parameterDName;

		public usp_GetField()
		{
			base.InitCommand("usp_GetField");
			ConfigParameter();
		}

		public System.String field
		{
			get
			{
				return (System.String)this.parameterfield.Value;
			}
			set
			{
				this.parameterfield.Value=value;
			}
		}

		public System.String TableName
		{
			get
			{
				return (System.String)this.parameterTableName.Value;
			}
			set
			{
				this.parameterTableName.Value=value;
			}
		}

		public System.String DName
		{
			get
			{
				return (System.String)this.parameterDName.Value;
			}
			set
			{
				this.parameterDName.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterfield=new SqlParameter();
			this.parameterfield.ParameterName="@field";
			this.parameterfield.SqlDbType=SqlDbType.VarChar;
			this.parameterfield.Size=-1;
			this.parameterfield.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfield);
			//--------------------------------------------------------
			this.parameterTableName=new SqlParameter();
			this.parameterTableName.ParameterName="@TableName";
			this.parameterTableName.SqlDbType=SqlDbType.VarChar;
			this.parameterTableName.Size=100;
			this.parameterTableName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterTableName);
			//--------------------------------------------------------
			this.parameterDName=new SqlParameter();
			this.parameterDName.ParameterName="@DName";
			this.parameterDName.SqlDbType=SqlDbType.VarChar;
			this.parameterDName.Size=-1;
			this.parameterDName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterDName);
		}
	}
}
