//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_Eqia_RPI_Basedata_Living_GetTwentyFourAVGValue : BaseProcedure
	{
		public usp_Eqia_RPI_Basedata_Living_GetTwentyFourAVGValue()
		{
			base.InitCommand("usp_Eqia_RPI_Basedata_Living_GetTwentyFourAVGValue");
			ConfigParameter();
		}

		public void ConfigParameter()
		{
		}
	}
}
