//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;

    public class usp_tblEQI_VerifyIdea_UpdateOrInsert : BaseProcedure
    {
        private SqlParameter parameterfldType;

        private SqlParameter parameterfldYear;

        private SqlParameter parameterfldMonth;

        private SqlParameter parameterfldDay;

        private SqlParameter parameterfldGrade;

        private SqlParameter parameterfldComment;

        public usp_tblEQI_VerifyIdea_UpdateOrInsert()
        {
            base.InitCommand("usp_tblEQI_VerifyIdea_UpdateOrInsert");
            ConfigParameter();
        }

        public System.String fldType
        {
            get
            {
                return (System.String)this.parameterfldType.Value;
            }
            set
            {
                this.parameterfldType.Value = value;
            }
        }

        public System.Decimal fldYear
        {
            get
            {
                return (System.Decimal)this.parameterfldYear.Value;
            }
            set
            {
                this.parameterfldYear.Value = value;
            }
        }

        public System.Decimal fldMonth
        {
            get
            {
                return (System.Decimal)this.parameterfldMonth.Value;
            }
            set
            {
                this.parameterfldMonth.Value = value;
            }
        }

        public System.Decimal fldDay
        {
            get
            {
                return (System.Decimal)this.parameterfldDay.Value;
            }
            set
            {
                this.parameterfldDay.Value = value;
            }
        }

        public System.Int32 fldGrade
        {
            get
            {
                return (System.Int32)this.parameterfldGrade.Value;
            }
            set
            {
                this.parameterfldGrade.Value = value;
            }
        }

        public System.String fldComment
        {
            get
            {
                return (System.String)this.parameterfldComment.Value;
            }
            set
            {
                this.parameterfldComment.Value = value;
            }
        }

        public void ConfigParameter()
        {
            //--------------------------------------------------------
            this.parameterfldType = new SqlParameter();
            this.parameterfldType.ParameterName = "@fldType";
            this.parameterfldType.SqlDbType = SqlDbType.VarChar;
            this.parameterfldType.Size = 10;
            this.parameterfldType.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldType);
            //--------------------------------------------------------
            this.parameterfldYear = new SqlParameter();
            this.parameterfldYear.ParameterName = "@fldYear";
            this.parameterfldYear.SqlDbType = SqlDbType.Decimal;
            this.parameterfldYear.Size = 5;
            this.parameterfldYear.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldYear);
            //--------------------------------------------------------
            this.parameterfldMonth = new SqlParameter();
            this.parameterfldMonth.ParameterName = "@fldMonth";
            this.parameterfldMonth.SqlDbType = SqlDbType.Decimal;
            this.parameterfldMonth.Size = 5;
            this.parameterfldMonth.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldMonth);
            //--------------------------------------------------------
            this.parameterfldDay = new SqlParameter();
            this.parameterfldDay.ParameterName = "@fldDay";
            this.parameterfldDay.SqlDbType = SqlDbType.Decimal;
            this.parameterfldDay.Size = 5;
            this.parameterfldDay.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldDay);
            //--------------------------------------------------------
            this.parameterfldGrade = new SqlParameter();
            this.parameterfldGrade.ParameterName = "@fldGrade";
            this.parameterfldGrade.SqlDbType = SqlDbType.Int;
            this.parameterfldGrade.Size = 4;
            this.parameterfldGrade.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldGrade);
            //--------------------------------------------------------
            this.parameterfldComment = new SqlParameter();
            this.parameterfldComment.ParameterName = "@fldComment";
            this.parameterfldComment.SqlDbType = SqlDbType.VarChar;
            this.parameterfldComment.Size = 500;
            this.parameterfldComment.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldComment);
        }
    }
}
