//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_base_eqiw_getdata_forgis : BaseProcedure
	{
		private SqlParameter parameterstcode;

		private SqlParameter parameterrcode;

		private SqlParameter parameterrscode;

		private SqlParameter parameteritemcodestr;

		private SqlParameter parameterbasetable;

		public usp_base_eqiw_getdata_forgis()
		{
			base.InitCommand("usp_base_eqiw_getdata_forgis");
			ConfigParameter();
		}

		public System.String stcode
		{
			get
			{
				return (System.String)this.parameterstcode.Value;
			}
			set
			{
				this.parameterstcode.Value=value;
			}
		}

		public System.String rcode
		{
			get
			{
				return (System.String)this.parameterrcode.Value;
			}
			set
			{
				this.parameterrcode.Value=value;
			}
		}

		public System.String rscode
		{
			get
			{
				return (System.String)this.parameterrscode.Value;
			}
			set
			{
				this.parameterrscode.Value=value;
			}
		}

		public System.String itemcodestr
		{
			get
			{
				return (System.String)this.parameteritemcodestr.Value;
			}
			set
			{
				this.parameteritemcodestr.Value=value;
			}
		}

		public System.String basetable
		{
			get
			{
				return (System.String)this.parameterbasetable.Value;
			}
			set
			{
				this.parameterbasetable.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterstcode=new SqlParameter();
			this.parameterstcode.ParameterName="@stcode";
			this.parameterstcode.SqlDbType=SqlDbType.VarChar;
			this.parameterstcode.Size=6;
			this.parameterstcode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterstcode);
			//--------------------------------------------------------
			this.parameterrcode=new SqlParameter();
			this.parameterrcode.ParameterName="@rcode";
			this.parameterrcode.SqlDbType=SqlDbType.VarChar;
			this.parameterrcode.Size=12;
			this.parameterrcode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterrcode);
			//--------------------------------------------------------
			this.parameterrscode=new SqlParameter();
			this.parameterrscode.ParameterName="@rscode";
			this.parameterrscode.SqlDbType=SqlDbType.VarChar;
			this.parameterrscode.Size=12;
			this.parameterrscode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterrscode);
			//--------------------------------------------------------
			this.parameteritemcodestr=new SqlParameter();
			this.parameteritemcodestr.ParameterName="@itemcodestr";
			this.parameteritemcodestr.SqlDbType=SqlDbType.VarChar;
			this.parameteritemcodestr.Size=-1;
			this.parameteritemcodestr.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameteritemcodestr);
			//--------------------------------------------------------
			this.parameterbasetable=new SqlParameter();
			this.parameterbasetable.ParameterName="@basetable";
			this.parameterbasetable.SqlDbType=SqlDbType.VarChar;
			this.parameterbasetable.Size=100;
			this.parameterbasetable.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterbasetable);
		}
	}
}
