//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_eqiw_r_autodataAvg : BaseProcedure
	{
		private SqlParameter parametertimetype;

		private SqlParameter parameterbdate;

		private SqlParameter parameteredate;

		private SqlParameter parameterrscode;

		private SqlParameter parameteritemcode;

		

		public usp_eqiw_r_autodataAvg()
		{
			base.InitCommand("usp_eqiw_r_autodataAvg");
			ConfigParameter();
		}

		public System.String timetype
        {
			get
			{
				return (System.String)this.parametertimetype.Value;
			}
			set
			{
				this.parametertimetype.Value=value;
			}
		}

		public System.String bdate
        {
			get
			{
				return (System.String)this.parameterbdate.Value;
			}
			set
			{
				this.parameterbdate.Value=value;
			}
		}

		public System.String edate
        {
			get
			{
				return (System.String)this.parameteredate.Value;
			}
			set
			{
				this.parameteredate.Value=value;
			}
		}

		public System.String rscode
        {
			get
			{
				return (System.String)this.parameterrscode.Value;
			}
			set
			{
				this.parameterrscode.Value=value;
			}
		}

		public System.String itemcode
        {
			get
			{
				return (System.String)this.parameteritemcode.Value;
			}
			set
			{
				this.parameteritemcode.Value=value;
			}
		}

	

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parametertimetype = new SqlParameter();
			this.parametertimetype.ParameterName= "@timetype";
			this.parametertimetype.SqlDbType=SqlDbType.VarChar;
			this.parametertimetype.Size=10;
			this.parametertimetype.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parametertimetype);
			//--------------------------------------------------------
			this.parameterbdate = new SqlParameter();
			this.parameterbdate.ParameterName= "@bdate";
			this.parameterbdate.SqlDbType=SqlDbType.VarChar;
			this.parameterbdate.Size=10;
			this.parameterbdate.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterbdate);
			//--------------------------------------------------------
			this.parameteredate = new SqlParameter();
			this.parameteredate.ParameterName= "@edate";
			this.parameteredate.SqlDbType=SqlDbType.VarChar;
			this.parameteredate.Size=10;
			this.parameteredate.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameteredate);
			//--------------------------------------------------------
			this.parameterrscode = new SqlParameter();
			this.parameterrscode.ParameterName= "@rscode";
			this.parameterrscode.SqlDbType=SqlDbType.VarChar;
			this.parameterrscode.Size=-1;
			this.parameterrscode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterrscode);
			//--------------------------------------------------------
			this.parameteritemcode = new SqlParameter();
			this.parameteritemcode.ParameterName= "@itemcode";
			this.parameteritemcode.SqlDbType=SqlDbType.VarChar;
			this.parameteritemcode.Size=-1;
			this.parameteritemcode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameteritemcode);		
		}
	}
}
