//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblEQIW_R_Basedata_Living_GetDayOrMonthAvgValue : BaseProcedure
	{
		private SqlParameter parameterAVGType;

		public usp_tblEQIW_R_Basedata_Living_GetDayOrMonthAvgValue()
		{
			base.InitCommand("usp_tblEQIW_R_Basedata_Living_GetDayOrMonthAvgValue");
			ConfigParameter();
		}

		public System.String AVGType
		{
			get
			{
				return (System.String)this.parameterAVGType.Value;
			}
			set
			{
				this.parameterAVGType.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterAVGType=new SqlParameter();
			this.parameterAVGType.ParameterName="@AVGType";
			this.parameterAVGType.SqlDbType=SqlDbType.VarChar;
			this.parameterAVGType.Size=10;
			this.parameterAVGType.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterAVGType);
		}
	}
}
