//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblFW_RegCity_Insert : BaseProcedure
	{
		private SqlParameter parameterfldAutoID;

		private SqlParameter parameterfldSTCode;

		private SqlParameter parameterfldSTName;

		private SqlParameter parameterfldParentID;

		private SqlParameter parameterfldNeedAuditing;

		public usp_tblFW_RegCity_Insert()
		{
			base.InitCommand("usp_tblFW_RegCity_Insert");
			ConfigParameter();
		}

		public System.Int32 fldAutoID
		{
			get
			{
				return (System.Int32)this.parameterfldAutoID.Value;
			}
			set
			{
				this.parameterfldAutoID.Value=value;
			}
		}

		public System.String fldSTCode
		{
			get
			{
				return (System.String)this.parameterfldSTCode.Value;
			}
			set
			{
				this.parameterfldSTCode.Value=value;
			}
		}

		public System.String fldSTName
		{
			get
			{
				return (System.String)this.parameterfldSTName.Value;
			}
			set
			{
				this.parameterfldSTName.Value=value;
			}
		}

		public System.Int32 fldParentID
		{
			get
			{
				return (System.Int32)this.parameterfldParentID.Value;
			}
			set
			{
				this.parameterfldParentID.Value=value;
			}
		}

		public System.Boolean fldNeedAuditing
		{
			get
			{
				return (System.Boolean)this.parameterfldNeedAuditing.Value;
			}
			set
			{
				this.parameterfldNeedAuditing.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterfldAutoID=new SqlParameter();
			this.parameterfldAutoID.ParameterName="@fldAutoID";
			this.parameterfldAutoID.SqlDbType=SqlDbType.Int;
			this.parameterfldAutoID.Size=4;
			this.parameterfldAutoID.Direction=ParameterDirection.InputOutput;
			base.m_cmd.Parameters.Add(this.parameterfldAutoID);
			//--------------------------------------------------------
			this.parameterfldSTCode=new SqlParameter();
			this.parameterfldSTCode.ParameterName="@fldSTCode";
			this.parameterfldSTCode.SqlDbType=SqlDbType.VarChar;
			this.parameterfldSTCode.Size=12;
			this.parameterfldSTCode.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldSTCode);
			//--------------------------------------------------------
			this.parameterfldSTName=new SqlParameter();
			this.parameterfldSTName.ParameterName="@fldSTName";
			this.parameterfldSTName.SqlDbType=SqlDbType.VarChar;
			this.parameterfldSTName.Size=20;
			this.parameterfldSTName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldSTName);
			//--------------------------------------------------------
			this.parameterfldParentID=new SqlParameter();
			this.parameterfldParentID.ParameterName="@fldParentID";
			this.parameterfldParentID.SqlDbType=SqlDbType.Int;
			this.parameterfldParentID.Size=4;
			this.parameterfldParentID.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldParentID);
			//--------------------------------------------------------
			this.parameterfldNeedAuditing=new SqlParameter();
			this.parameterfldNeedAuditing.ParameterName="@fldNeedAuditing";
			this.parameterfldNeedAuditing.SqlDbType=SqlDbType.Bit;
			this.parameterfldNeedAuditing.Size=1;
			this.parameterfldNeedAuditing.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldNeedAuditing);
		}
	}
}
