//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblFW_Reports_ByRoleID : BaseProcedure
	{
		private SqlParameter parameterfldRoleID;

		private SqlParameter parameterfldName;

		public usp_tblFW_Reports_ByRoleID()
		{
			base.InitCommand("usp_tblFW_Reports_ByRoleID");
			ConfigParameter();
		}

		public System.Int32 fldRoleID
		{
			get
			{
				return (System.Int32)this.parameterfldRoleID.Value;
			}
			set
			{
				this.parameterfldRoleID.Value=value;
			}
		}

		public System.String fldName
		{
			get
			{
				return (System.String)this.parameterfldName.Value;
			}
			set
			{
				this.parameterfldName.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterfldRoleID=new SqlParameter();
			this.parameterfldRoleID.ParameterName="@fldRoleID";
			this.parameterfldRoleID.SqlDbType=SqlDbType.Int;
			this.parameterfldRoleID.Size=4;
			this.parameterfldRoleID.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldRoleID);
			//--------------------------------------------------------
			this.parameterfldName=new SqlParameter();
			this.parameterfldName.ParameterName="@fldName";
			this.parameterfldName.SqlDbType=SqlDbType.VarChar;
			this.parameterfldName.Size=100;
			this.parameterfldName.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldName);
		}
	}
}
