//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	public class usp_tblItem_Recording_Insert : BaseProcedure
	{
		private SqlParameter parameterfldAutoID;

		private SqlParameter parameterfldType;

		private SqlParameter parameterfldRange;

		private SqlParameter parameterfldDate;

		public usp_tblItem_Recording_Insert()
		{
			base.InitCommand("usp_tblItem_Recording_Insert");
			ConfigParameter();
		}

		public System.Int32 fldAutoID
		{
			get
			{
				return (System.Int32)this.parameterfldAutoID.Value;
			}
			set
			{
				this.parameterfldAutoID.Value=value;
			}
		}

		public System.String fldType
		{
			get
			{
				return (System.String)this.parameterfldType.Value;
			}
			set
			{
				this.parameterfldType.Value=value;
			}
		}

		public System.String fldRange
		{
			get
			{
				return (System.String)this.parameterfldRange.Value;
			}
			set
			{
				this.parameterfldRange.Value=value;
			}
		}

		public System.String fldDate
		{
			get
			{
				return (System.String)this.parameterfldDate.Value;
			}
			set
			{
				this.parameterfldDate.Value=value;
			}
		}

		public void ConfigParameter()
		{
			//--------------------------------------------------------
			this.parameterfldAutoID=new SqlParameter();
			this.parameterfldAutoID.ParameterName="@fldAutoID";
			this.parameterfldAutoID.SqlDbType=SqlDbType.Int;
			this.parameterfldAutoID.Size=4;
			this.parameterfldAutoID.Direction=ParameterDirection.InputOutput;
			base.m_cmd.Parameters.Add(this.parameterfldAutoID);
			//--------------------------------------------------------
			this.parameterfldType=new SqlParameter();
			this.parameterfldType.ParameterName="@fldType";
			this.parameterfldType.SqlDbType=SqlDbType.VarChar;
			this.parameterfldType.Size=10;
			this.parameterfldType.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldType);
			//--------------------------------------------------------
			this.parameterfldRange=new SqlParameter();
			this.parameterfldRange.ParameterName="@fldRange";
			this.parameterfldRange.SqlDbType=SqlDbType.VarChar;
			this.parameterfldRange.Size=200;
			this.parameterfldRange.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldRange);
			//--------------------------------------------------------
			this.parameterfldDate=new SqlParameter();
			this.parameterfldDate.ParameterName="@fldDate";
			this.parameterfldDate.SqlDbType=SqlDbType.VarChar;
			this.parameterfldDate.Size=50;
			this.parameterfldDate.Direction=ParameterDirection.Input;
			base.m_cmd.Parameters.Add(this.parameterfldDate);
		}
	}
}
