//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.DataSource.DataAccess
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;

    public class usp_tblEQIA_RPI_Basedata_Pre_UpdateItemValueBytable : BaseProcedure
    {
        private SqlParameter parameterfldAutoID;

        private SqlParameter parameterfldItemCode;

        private SqlParameter parameterfldItemValue;

        private SqlParameter parametertable;

        public usp_tblEQIA_RPI_Basedata_Pre_UpdateItemValueBytable()
        {
            base.InitCommand("usp_tblEQIA_RPI_Basedata_Pre_UpdateItemValueBytable");
            ConfigParameter();
        }

        public System.String fldAutoID
        {
            get
            {
                return (System.String)this.parameterfldAutoID.Value;
            }
            set
            {
                this.parameterfldAutoID.Value = value;
            }
        }

        public System.String fldItemCode
        {
            get
            {
                return (System.String)this.parameterfldItemCode.Value;
            }
            set
            {
                this.parameterfldItemCode.Value = value;
            }
        }

        public System.String fldItemValue
        {
            get
            {
                return (System.String)this.parameterfldItemValue.Value;
            }
            set
            {
                this.parameterfldItemValue.Value = value;
            }
        }

        public System.String table
        {
            get
            {
                return (System.String)this.parametertable.Value;
            }
            set
            {
                this.parametertable.Value = value;
            }
        }

        public void ConfigParameter()
        {
            //--------------------------------------------------------
            this.parameterfldAutoID = new SqlParameter();
            this.parameterfldAutoID.ParameterName = "@fldAutoID";
            this.parameterfldAutoID.SqlDbType = SqlDbType.VarChar;
            this.parameterfldAutoID.Size = -1;
            this.parameterfldAutoID.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldAutoID);
            //--------------------------------------------------------
            this.parameterfldItemCode = new SqlParameter();
            this.parameterfldItemCode.ParameterName = "@fldItemCode";
            this.parameterfldItemCode.SqlDbType = SqlDbType.VarChar;
            this.parameterfldItemCode.Size = 10;
            this.parameterfldItemCode.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldItemCode);
            //--------------------------------------------------------
            this.parameterfldItemValue = new SqlParameter();
            this.parameterfldItemValue.ParameterName = "@fldItemValue";
            this.parameterfldItemValue.SqlDbType = SqlDbType.VarChar;
            this.parameterfldItemValue.Size = 10;
            this.parameterfldItemValue.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parameterfldItemValue);
            //--------------------------------------------------------
            this.parametertable = new SqlParameter();
            this.parametertable.ParameterName = "@table";
            this.parametertable.SqlDbType = SqlDbType.VarChar;
            this.parametertable.Size = 100;
            this.parametertable.Direction = ParameterDirection.Input;
            base.m_cmd.Parameters.Add(this.parametertable);
        }
    }
}
