//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.Presistence.DataEntity
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	[Serializable]
	public class tblRSNameCorItemName : BaseDataEntity
	{
		[AttributePK]
		private System.Int32 m_fldAutoId;

		private System.String m_fldRSCode;

		private System.String m_fldRSCName;

		private System.String m_fldItemCode;

		private System.String m_fldItemName;

		public tblRSNameCorItemName()
		{
			base.InitMetaData();
		}

		/// <summary>
		/// 复制实体类的内容
		/// </summary>
		/// <returns></returns>
		public tblRSNameCorItemName Clone()
		{
			tblRSNameCorItemName objNew = (tblRSNameCorItemName)this.MemberwiseClone();
			return objNew;
		}

		public System.Int32 fldAutoId
		{
			get
			{
				return this.m_fldAutoId;
			}
			set
			{
				this.m_fldAutoId=value;
			}
		}

		public System.String fldRSCode
		{
			get
			{
				return this.m_fldRSCode;
			}
			set
			{
				this.m_fldRSCode=value;
			}
		}

		public System.String fldRSCName
		{
			get
			{
				return this.m_fldRSCName;
			}
			set
			{
				this.m_fldRSCName=value;
			}
		}

		public System.String fldItemCode
		{
			get
			{
				return this.m_fldItemCode;
			}
			set
			{
				this.m_fldItemCode=value;
			}
		}

		public System.String fldItemName
		{
			get
			{
				return this.m_fldItemName;
			}
			set
			{
				this.m_fldItemName=value;
			}
		}

	}
}
