//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.Presistence.DataEntity
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;

    [Serializable]
    public class tblDT_DN_TempletInfo : BaseDataEntity
    {
        [AttributePK]
        private System.Int32 m_fldAutoID;

        private System.String m_fldTableName;

        private System.String m_fldTableDesc;

        private System.Int16 m_fldTable_Type;

        private System.Int16 m_fldSort;

        private System.String m_fldExportGetDataSql;

        private System.Int16 m_fldModule;

        private System.Int16 m_fldPoint_Type;


        public tblDT_DN_TempletInfo()
        {
            base.InitMetaData();
        }

        /// <summary>
        /// 复制实体类的内容
        /// </summary>
        /// <returns></returns>
        public tblDT_DN_TempletInfo Clone()
        {
            tblDT_DN_TempletInfo objNew = (tblDT_DN_TempletInfo)this.MemberwiseClone();
            return objNew;
        }

        public System.Int32 fldAutoID
        {
            get
            {
                return this.m_fldAutoID;
            }
            set
            {
                this.m_fldAutoID = value;
            }
        }

        public System.String fldTableName
        {
            get
            {
                return this.m_fldTableName;
            }
            set
            {
                this.m_fldTableName = value;
            }
        }

        public System.String fldTableDesc
        {
            get
            {
                return this.m_fldTableDesc;
            }
            set
            {
                this.m_fldTableDesc = value;
            }
        }

        public System.Int16 fldTable_Type
        {
            get
            {
                return this.m_fldTable_Type;
            }
            set
            {
                this.m_fldTable_Type = value;
            }
        }

        public System.Int16 fldSort
        {
            get
            {
                return this.m_fldSort;
            }
            set
            {
                this.m_fldSort = value;
            }
        }

        public System.String fldExportGetDataSql
        {
            get
            {
                return this.m_fldExportGetDataSql;
            }
            set
            {
                this.m_fldExportGetDataSql = value;
            }
        }

        public System.Int16 fldModule
        {
            get
            {
                return this.m_fldModule;
            }
            set
            {
                this.m_fldModule = value;
            }
        }

        public System.Int16 fldPoint_Type
        {
            get
            {
                return this.m_fldPoint_Type;
            }
            set
            {
                this.m_fldPoint_Type = value;
            }
        }

        public string fldModuleStr
        {
            get;
            set;
        }

        public bool fldPortrait
        {
            get;
            set;
        }
    }
}
