//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.Presistence.DataEntity
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	[Serializable]
	public class tblEQIN_A_Point : BaseDataEntity
	{
		[AttributePK]
		private System.Int32 m_fldAutoID;

		private System.String m_fldSTCode;

		private System.String m_fldSTName;

		private System.Decimal m_fldYear;

		private System.String m_fldGDCODE;

		private System.String m_fldGDNAME;

		private System.Decimal m_fldGRIDL;

		private System.Decimal m_fldGRIDW;

		private System.String m_fldNDISC;

		private System.String m_fldNSC;

		private System.Decimal m_fldGPOPUL;

		private System.String m_fldLCODE;

		private System.String m_fldLNAME;

		private System.String m_fldAttribute;

		private System.Int32 m_fldSort;

		public tblEQIN_A_Point()
		{
			base.InitMetaData();
		}

		/// <summary>
		/// 复制实体类的内容
		/// </summary>
		/// <returns></returns>
		public tblEQIN_A_Point Clone()
		{
			tblEQIN_A_Point objNew = (tblEQIN_A_Point)this.MemberwiseClone();
			return objNew;
		}

		public System.Int32 fldAutoID
		{
			get
			{
				return this.m_fldAutoID;
			}
			set
			{
				this.m_fldAutoID=value;
			}
		}

		public System.String fldSTCode
		{
			get
			{
				return this.m_fldSTCode;
			}
			set
			{
				this.m_fldSTCode=value;
			}
		}

		public System.String fldSTName
		{
			get
			{
				return this.m_fldSTName;
			}
			set
			{
				this.m_fldSTName=value;
			}
		}

		public System.Decimal fldYear
		{
			get
			{
				return this.m_fldYear;
			}
			set
			{
				this.m_fldYear=value;
			}
		}

		public System.String fldGDCODE
		{
			get
			{
				return this.m_fldGDCODE;
			}
			set
			{
				this.m_fldGDCODE=value;
			}
		}

		public System.String fldGDNAME
		{
			get
			{
				return this.m_fldGDNAME;
			}
			set
			{
				this.m_fldGDNAME=value;
			}
		}

		public System.Decimal fldGRIDL
		{
			get
			{
				return this.m_fldGRIDL;
			}
			set
			{
				this.m_fldGRIDL=value;
			}
		}

		public System.Decimal fldGRIDW
		{
			get
			{
				return this.m_fldGRIDW;
			}
			set
			{
				this.m_fldGRIDW=value;
			}
		}

		public System.String fldNDISC
		{
			get
			{
				return this.m_fldNDISC;
			}
			set
			{
				this.m_fldNDISC=value;
			}
		}

		public System.String fldNSC
		{
			get
			{
				return this.m_fldNSC;
			}
			set
			{
				this.m_fldNSC=value;
			}
		}

		public System.Decimal fldGPOPUL
		{
			get
			{
				return this.m_fldGPOPUL;
			}
			set
			{
				this.m_fldGPOPUL=value;
			}
		}

		public System.String fldLCODE
		{
			get
			{
				return this.m_fldLCODE;
			}
			set
			{
				this.m_fldLCODE=value;
			}
		}

		public System.String fldLNAME
		{
			get
			{
				return this.m_fldLNAME;
			}
			set
			{
				this.m_fldLNAME=value;
			}
		}

		public System.String fldAttribute
		{
			get
			{
				return this.m_fldAttribute;
			}
			set
			{
				this.m_fldAttribute=value;
			}
		}

		public System.Int32 fldSort
		{
			get
			{
				return this.m_fldSort;
			}
			set
			{
				this.m_fldSort=value;
			}
		}

	}
}
