//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.Presistence.DataEntity
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	[Serializable]
	public class tblEQISO_PISTG : BaseDataEntity
	{
		[AttributePK]
		private System.Int32 m_fldAutoID;

		private System.String m_fldStandardName;

		private System.String m_fldStandardNum;

		private System.String m_fldPLevel;

		private System.Decimal m_fldMinAPI;

		private System.Decimal m_fldMaxAPI;

		private System.String m_fldAQS;

		public tblEQISO_PISTG()
		{
			base.InitMetaData();
		}

		/// <summary>
		/// 复制实体类的内容
		/// </summary>
		/// <returns></returns>
		public tblEQISO_PISTG Clone()
		{
			tblEQISO_PISTG objNew = (tblEQISO_PISTG)this.MemberwiseClone();
			return objNew;
		}

		public System.Int32 fldAutoID
		{
			get
			{
				return this.m_fldAutoID;
			}
			set
			{
				this.m_fldAutoID=value;
			}
		}

		public System.String fldStandardName
		{
			get
			{
				return this.m_fldStandardName;
			}
			set
			{
				this.m_fldStandardName=value;
			}
		}

		public System.String fldStandardNum
		{
			get
			{
				return this.m_fldStandardNum;
			}
			set
			{
				this.m_fldStandardNum=value;
			}
		}

		public System.String fldPLevel
		{
			get
			{
				return this.m_fldPLevel;
			}
			set
			{
				this.m_fldPLevel=value;
			}
		}

		public System.Decimal fldMinAPI
		{
			get
			{
				return this.m_fldMinAPI;
			}
			set
			{
				this.m_fldMinAPI=value;
			}
		}

		public System.Decimal fldMaxAPI
		{
			get
			{
				return this.m_fldMaxAPI;
			}
			set
			{
				this.m_fldMaxAPI=value;
			}
		}

		public System.String fldAQS
		{
			get
			{
				return this.m_fldAQS;
			}
			set
			{
				this.m_fldAQS=value;
			}
		}

	}
}
