//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.Presistence.DataEntity
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;

    [Serializable]
    public class tbleqi_ThreeVerify : BaseDataEntity
    {
        [AttributePK]
        private System.Int64 m_fldAutoID;

        private System.String m_fldType;

        private System.Int64 m_fldTypeID;

        private System.String m_fldComment;

        private System.String m_fldAudType;

        private System.String m_ThreeVerify1;

        private System.String m_ThreeVerify2;

        private System.String m_ThreeVerify3;

        private System.String m_fldPName;

        private System.String m_fldDataTime;

        public tbleqi_ThreeVerify()
        {
            base.InitMetaData();
        }

        /// <summary>
        /// 复制实体类的内容
        /// </summary>
        /// <returns></returns>
        public tbleqi_ThreeVerify Clone()
        {
            tbleqi_ThreeVerify objNew = (tbleqi_ThreeVerify)this.MemberwiseClone();
            return objNew;
        }

        public System.Int64 fldAutoID
        {
            get
            {
                return this.m_fldAutoID;
            }
            set
            {
                this.m_fldAutoID = value;
            }
        }

        public System.String fldType
        {
            get
            {
                return this.m_fldType;
            }
            set
            {
                this.m_fldType = value;
            }
        }

        public System.Int64 fldTypeID
        {
            get
            {
                return this.m_fldTypeID;
            }
            set
            {
                this.m_fldTypeID = value;
            }
        }

        public System.String fldComment
        {
            get
            {
                return this.m_fldComment;
            }
            set
            {
                this.m_fldComment = value;
            }
        }

        public System.String fldAudType
        {
            get
            {
                return this.m_fldAudType;
            }
            set
            {
                this.m_fldAudType = value;
            }
        }

        public System.String ThreeVerify1
        {
            get
            {
                return this.m_ThreeVerify1;
            }
            set
            {
                this.m_ThreeVerify1 = value;
            }
        }

        public System.String ThreeVerify2
        {
            get
            {
                return this.m_ThreeVerify2;
            }
            set
            {
                this.m_ThreeVerify2 = value;
            }
        }

        public System.String ThreeVerify3
        {
            get
            {
                return this.m_ThreeVerify3;
            }
            set
            {
                this.m_ThreeVerify3 = value;
            }
        }

        public System.String fldPName
        {
            get
            {
                return this.m_fldPName;
            }
            set
            {
                this.m_fldPName = value;
            }
        }

        public System.String fldDataTime
        {
            get
            {
                return this.m_fldDataTime;
            }
            set
            {
                this.m_fldDataTime = value;
            }
        }

    }
}
