//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.Presistence.DataEntity
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	[Serializable]
	public class tblEQIS_W_Point : BaseDataEntity
	{
		[AttributePK]
		private System.Int32 m_fldAutoID;

		private System.String m_fldSeaAreaCode;

		private System.String m_fldSeaAreaName;

		private System.String m_fldSeaRegionCode;

		private System.String m_fldSeaRegionName;

		private System.String m_fldProvinceCode;

		private System.String m_fldProvinceName;

		private System.String m_fldSTCode;

		private System.String m_fldSTName;

		private System.Decimal m_fldYear;

		private System.String m_fldPCode;

		private System.String m_fldPName;

		private System.Int32 m_fldFun;

		private System.Int16 m_fldPLevel;

		private System.String m_fldLOD;

		private System.String m_fldLOM;

		private System.String m_fldLOS;

		private System.String m_fldLAD;

		private System.String m_fldLAM;

		private System.String m_fldLAS;

		private System.Decimal m_fldPArea;

		private System.String m_fldAttribute;

		private System.Int32 m_fldSort;

		public tblEQIS_W_Point()
		{
			base.InitMetaData();
		}

		/// <summary>
		/// 复制实体类的内容
		/// </summary>
		/// <returns></returns>
		public tblEQIS_W_Point Clone()
		{
			tblEQIS_W_Point objNew = (tblEQIS_W_Point)this.MemberwiseClone();
			return objNew;
		}

		public System.Int32 fldAutoID
		{
			get
			{
				return this.m_fldAutoID;
			}
			set
			{
				this.m_fldAutoID=value;
			}
		}

		public System.String fldSeaAreaCode
		{
			get
			{
				return this.m_fldSeaAreaCode;
			}
			set
			{
				this.m_fldSeaAreaCode=value;
			}
		}

		public System.String fldSeaAreaName
		{
			get
			{
				return this.m_fldSeaAreaName;
			}
			set
			{
				this.m_fldSeaAreaName=value;
			}
		}

		public System.String fldSeaRegionCode
		{
			get
			{
				return this.m_fldSeaRegionCode;
			}
			set
			{
				this.m_fldSeaRegionCode=value;
			}
		}

		public System.String fldSeaRegionName
		{
			get
			{
				return this.m_fldSeaRegionName;
			}
			set
			{
				this.m_fldSeaRegionName=value;
			}
		}

		public System.String fldProvinceCode
		{
			get
			{
				return this.m_fldProvinceCode;
			}
			set
			{
				this.m_fldProvinceCode=value;
			}
		}

		public System.String fldProvinceName
		{
			get
			{
				return this.m_fldProvinceName;
			}
			set
			{
				this.m_fldProvinceName=value;
			}
		}

		public System.String fldSTCode
		{
			get
			{
				return this.m_fldSTCode;
			}
			set
			{
				this.m_fldSTCode=value;
			}
		}

		public System.String fldSTName
		{
			get
			{
				return this.m_fldSTName;
			}
			set
			{
				this.m_fldSTName=value;
			}
		}

		public System.Decimal fldYear
		{
			get
			{
				return this.m_fldYear;
			}
			set
			{
				this.m_fldYear=value;
			}
		}

		public System.String fldPCode
		{
			get
			{
				return this.m_fldPCode;
			}
			set
			{
				this.m_fldPCode=value;
			}
		}

		public System.String fldPName
		{
			get
			{
				return this.m_fldPName;
			}
			set
			{
				this.m_fldPName=value;
			}
		}

		public System.Int32 fldFun
		{
			get
			{
				return this.m_fldFun;
			}
			set
			{
				this.m_fldFun=value;
			}
		}

		public System.Int16 fldPLevel
		{
			get
			{
				return this.m_fldPLevel;
			}
			set
			{
				this.m_fldPLevel=value;
			}
		}

		public System.String fldLOD
		{
			get
			{
				return this.m_fldLOD;
			}
			set
			{
				this.m_fldLOD=value;
			}
		}

		public System.String fldLOM
		{
			get
			{
				return this.m_fldLOM;
			}
			set
			{
				this.m_fldLOM=value;
			}
		}

		public System.String fldLOS
		{
			get
			{
				return this.m_fldLOS;
			}
			set
			{
				this.m_fldLOS=value;
			}
		}

		public System.String fldLAD
		{
			get
			{
				return this.m_fldLAD;
			}
			set
			{
				this.m_fldLAD=value;
			}
		}

		public System.String fldLAM
		{
			get
			{
				return this.m_fldLAM;
			}
			set
			{
				this.m_fldLAM=value;
			}
		}

		public System.String fldLAS
		{
			get
			{
				return this.m_fldLAS;
			}
			set
			{
				this.m_fldLAS=value;
			}
		}

		public System.Decimal fldPArea
		{
			get
			{
				return this.m_fldPArea;
			}
			set
			{
				this.m_fldPArea=value;
			}
		}

		public System.String fldAttribute
		{
			get
			{
				return this.m_fldAttribute;
			}
			set
			{
				this.m_fldAttribute=value;
			}
		}

		public System.Int32 fldSort
		{
			get
			{
				return this.m_fldSort;
			}
			set
			{
				this.m_fldSort=value;
			}
		}

	}
}
