//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.Presistence.DataEntity
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;

    [Serializable]
    public class tblEQIN_M_Point : BaseDataEntity
    {
        [AttributePK]
        private System.Int32 m_fldAutoID;

        private System.String m_fldSTCode;

        private System.String m_fldSTName;

        private System.Decimal m_fldYear;

        private System.String m_fldPCode;

        private System.String m_fldPName;

        private System.Decimal m_fldGRIDL;

        private System.String m_fldGRIDW;

        private System.String m_fldYawpType;

        private System.String m_fldRoadType;

        private System.String m_fldLCODE;

        private System.String m_fldLNAME;

        private System.Int32 m_fldReally;

        private System.Int32 m_fldSort;

        private System.String m_fldRemark;

        private System.String m_fldStaLod;

        private System.String m_fldStaLad;

        private System.Decimal m_fldSLod;

        private System.Decimal m_fldSLad;

        public tblEQIN_M_Point()
        {
            base.InitMetaData();
        }

        /// <summary>
        /// 复制实体类的内容
        /// </summary>
        /// <returns></returns>
        public tblEQIN_M_Point Clone()
        {
            tblEQIN_M_Point objNew = (tblEQIN_M_Point)this.MemberwiseClone();
            return objNew;
        }

        public System.Int32 fldAutoID
        {
            get
            {
                return this.m_fldAutoID;
            }
            set
            {
                this.m_fldAutoID = value;
            }
        }

        public System.String fldSTCode
        {
            get
            {
                return this.m_fldSTCode;
            }
            set
            {
                this.m_fldSTCode = value;
            }
        }

        public System.String fldSTName
        {
            get
            {
                return this.m_fldSTName;
            }
            set
            {
                this.m_fldSTName = value;
            }
        }

        public System.Decimal fldYear
        {
            get
            {
                return this.m_fldYear;
            }
            set
            {
                this.m_fldYear = value;
            }
        }

        public System.String fldPCode
        {
            get
            {
                return this.m_fldPCode;
            }
            set
            {
                this.m_fldPCode = value;
            }
        }

        public System.String fldPName
        {
            get
            {
                return this.m_fldPName;
            }
            set
            {
                this.m_fldPName = value;
            }
        }

        public System.Decimal fldGRIDL
        {
            get
            {
                return this.m_fldGRIDL;
            }
            set
            {
                this.m_fldGRIDL = value;
            }
        }

        public System.String fldGRIDW
        {
            get
            {
                return this.m_fldGRIDW;
            }
            set
            {
                this.m_fldGRIDW = value;
            }
        }

        public System.String fldYawpType
        {
            get
            {
                return this.m_fldYawpType;
            }
            set
            {
                this.m_fldYawpType = value;
            }
        }

        public System.String fldRoadType
        {
            get
            {
                return this.m_fldRoadType;
            }
            set
            {
                this.m_fldRoadType = value;
            }
        }

        public System.String fldLCODE
        {
            get
            {
                return this.m_fldLCODE;
            }
            set
            {
                this.m_fldLCODE = value;
            }
        }

        public System.String fldLNAME
        {
            get
            {
                return this.m_fldLNAME;
            }
            set
            {
                this.m_fldLNAME = value;
            }
        }

        public System.Int32 fldReally
        {
            get
            {
                return this.m_fldReally;
            }
            set
            {
                this.m_fldReally = value;
            }
        }

        public System.Int32 fldSort
        {
            get
            {
                return this.m_fldSort;
            }
            set
            {
                this.m_fldSort = value;
            }
        }

        public System.String fldRemark
        {
            get
            {
                return this.m_fldRemark;
            }
            set
            {
                this.m_fldRemark = value;
            }
        }

        public System.String fldStaLod
        {
            get
            {
                return this.m_fldStaLod;
            }
            set
            {
                this.m_fldStaLod = value;
            }
        }

        public System.String fldStaLad
        {
            get
            {
                return this.m_fldStaLad;
            }
            set
            {
                this.m_fldStaLad = value;
            }
        }

        public System.Decimal fldSLod
        {
            get
            {
                return this.m_fldSLod;
            }
            set
            {
                this.m_fldSLod = value;
            }
        }
        public System.Decimal fldSLad
        {
            get
            {
                return this.m_fldSLad;
            }
            set
            {
                this.m_fldSLad = value;
            }
        }
    }
}
