//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.Presistence.DataEntity
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	[Serializable]
	public class tblEQI_DataImport_Remark : BaseDataEntity
	{
		[AttributePK]
		private System.Int64 m_fldAutoID;

		private System.String m_fldObject;

		private System.String m_fldRSInfo;

		private System.String m_fldDate;

		private System.String m_fldRemark;

		public tblEQI_DataImport_Remark()
		{
			base.InitMetaData();
		}

		/// <summary>
		/// 复制实体类的内容
		/// </summary>
		/// <returns></returns>
		public tblEQI_DataImport_Remark Clone()
		{
			tblEQI_DataImport_Remark objNew = (tblEQI_DataImport_Remark)this.MemberwiseClone();
			return objNew;
		}

		public System.Int64 fldAutoID
		{
			get
			{
				return this.m_fldAutoID;
			}
			set
			{
				this.m_fldAutoID=value;
			}
		}

		public System.String fldObject
		{
			get
			{
				return this.m_fldObject;
			}
			set
			{
				this.m_fldObject=value;
			}
		}

		public System.String fldRSInfo
		{
			get
			{
				return this.m_fldRSInfo;
			}
			set
			{
				this.m_fldRSInfo=value;
			}
		}

		public System.String fldDate
		{
			get
			{
				return this.m_fldDate;
			}
			set
			{
				this.m_fldDate=value;
			}
		}

		public System.String fldRemark
		{
			get
			{
				return this.m_fldRemark;
			}
			set
			{
				this.m_fldRemark=value;
			}
		}

	}
}
