//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.Presistence.DataEntity
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Data.SqlTypes;
    using System.Xml;
    using System.Reflection;

    [Serializable]
    public class tblEQIN_T_BaseData : BaseDataEntity
    {
        [AttributePK]
        private System.Int64 m_fldAutoID;

        private System.String m_fldSTCode;

        private System.String m_fldRDCode;

        private System.Decimal m_fldYear;

        private System.Decimal m_fldMonth;

        private System.Decimal m_fldDay;

        private System.Decimal m_fldHour;

        private System.Decimal m_fldMinute;

        private System.Int32 m_fldTimelen;

        private System.String m_fldDN;

        private System.Decimal m_fldPTrafic;

        private System.Decimal m_fldLEQA;

        private System.Decimal m_fldL10A;

        private System.Decimal m_fldL50A;

        private System.Decimal m_fldL90A;

        private System.Decimal m_fldLmax;

        private System.Decimal m_fldLmin;

        private System.Int32 m_fldUserID;

        public tblEQIN_T_BaseData()
        {
            base.InitMetaData();
        }

        /// <summary>
        /// 复制实体类的内容
        /// </summary>
        /// <returns></returns>
        public tblEQIN_T_BaseData Clone()
        {
            tblEQIN_T_BaseData objNew = (tblEQIN_T_BaseData)this.MemberwiseClone();
            return objNew;
        }

        public System.Int64 fldAutoID
        {
            get
            {
                return this.m_fldAutoID;
            }
            set
            {
                this.m_fldAutoID = value;
            }
        }

        public System.String fldSTCode
        {
            get
            {
                return this.m_fldSTCode;
            }
            set
            {
                this.m_fldSTCode = value;
            }
        }

        public System.String fldRDCode
        {
            get
            {
                return this.m_fldRDCode;
            }
            set
            {
                this.m_fldRDCode = value;
            }
        }

        public System.Decimal fldYear
        {
            get
            {
                return this.m_fldYear;
            }
            set
            {
                this.m_fldYear = value;
            }
        }

        public System.Decimal fldMonth
        {
            get
            {
                return this.m_fldMonth;
            }
            set
            {
                this.m_fldMonth = value;
            }
        }

        public System.Decimal fldDay
        {
            get
            {
                return this.m_fldDay;
            }
            set
            {
                this.m_fldDay = value;
            }
        }

        public System.Decimal fldHour
        {
            get
            {
                return this.m_fldHour;
            }
            set
            {
                this.m_fldHour = value;
            }
        }

        public System.Decimal fldMinute
        {
            get
            {
                return this.m_fldMinute;
            }
            set
            {
                this.m_fldMinute = value;
            }
        }

        public System.Int32 fldTimelen
        {
            get
            {
                return this.m_fldTimelen;
            }
            set
            {
                this.m_fldTimelen = value;
            }
        }

        public System.String fldDN
        {
            get
            {
                return this.m_fldDN;
            }
            set
            {
                this.m_fldDN = value;
            }
        }

        public System.Decimal fldPTrafic
        {
            get
            {
                return this.m_fldPTrafic;
            }
            set
            {
                this.m_fldPTrafic = value;
            }
        }

        public System.Decimal fldLEQA
        {
            get
            {
                return this.m_fldLEQA;
            }
            set
            {
                this.m_fldLEQA = value;
            }
        }

        public System.Decimal fldL10A
        {
            get
            {
                return this.m_fldL10A;
            }
            set
            {
                this.m_fldL10A = value;
            }
        }

        public System.Decimal fldL50A
        {
            get
            {
                return this.m_fldL50A;
            }
            set
            {
                this.m_fldL50A = value;
            }
        }

        public System.Decimal fldL90A
        {
            get
            {
                return this.m_fldL90A;
            }
            set
            {
                this.m_fldL90A = value;
            }
        }

        public System.Decimal fldLmax
        {
            get
            {
                return this.m_fldLmax;
            }
            set
            {
                this.m_fldLmax = value;
            }
        }

        public System.Decimal fldLmin
        {
            get
            {
                return this.m_fldLmin;
            }
            set
            {
                this.m_fldLmin = value;
            }
        }

        public System.Int32 fldUserID
        {
            get
            {
                return this.m_fldUserID;
            }
            set
            {
                this.m_fldUserID = value;
            }
        }

    }
}
