//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: v2.0.50727
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DDYZ.Ensis.Presistence.DataEntity
{
	using System;
	using System.Data;
	using System.Data.SqlClient;
	using System.Data.SqlTypes;
	using System.Xml;
	using System.Reflection;

	[Serializable]
	public class tblEQI_Point_Group : BaseDataEntity
	{
		[AttributePK]
		private System.Int32 m_fldAutoID;

		private System.String m_fldObject;

		private System.Int16 m_fldType;

		private System.String m_fldName;

		private System.Int32 m_fldUserID;

		private System.Decimal m_fldYear;

		private System.String m_fldPointContent;

		public tblEQI_Point_Group()
		{
			base.InitMetaData();
		}

		/// <summary>
		/// 复制实体类的内容
		/// </summary>
		/// <returns></returns>
		public tblEQI_Point_Group Clone()
		{
			tblEQI_Point_Group objNew = (tblEQI_Point_Group)this.MemberwiseClone();
			return objNew;
		}

		public System.Int32 fldAutoID
		{
			get
			{
				return this.m_fldAutoID;
			}
			set
			{
				this.m_fldAutoID=value;
			}
		}

		public System.String fldObject
		{
			get
			{
				return this.m_fldObject;
			}
			set
			{
				this.m_fldObject=value;
			}
		}

		public System.Int16 fldType
		{
			get
			{
				return this.m_fldType;
			}
			set
			{
				this.m_fldType=value;
			}
		}

		public System.String fldName
		{
			get
			{
				return this.m_fldName;
			}
			set
			{
				this.m_fldName=value;
			}
		}

		public System.Int32 fldUserID
		{
			get
			{
				return this.m_fldUserID;
			}
			set
			{
				this.m_fldUserID=value;
			}
		}

		public System.Decimal fldYear
		{
			get
			{
				return this.m_fldYear;
			}
			set
			{
				this.m_fldYear=value;
			}
		}

		public System.String fldPointContent
		{
			get
			{
				return this.m_fldPointContent;
			}
			set
			{
				this.m_fldPointContent=value;
			}
		}

	}
}
